/*
 * generated by Xtext 2.40.0
 */
package org.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.ide.contentassist.antlr.internal.InternalSpiceParser;
import org.xtext.services.SpiceGrammarAccess;

public class SpiceParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SpiceGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SpiceGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getAlternatives_1(), "rule__Xmod_Exception__Alternatives_1");
			builder.put(grammarAccess.getXmod_ExceptionKind_UnfilteredAccess().getAlternatives(), "rule__Xmod_ExceptionKind_Unfiltered__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getXmod_ExceptionReactionAccess().getAlternatives(), "rule__Xmod_ExceptionReaction__Alternatives");
			builder.put(grammarAccess.getXmod_ExceptionKindAccess().getAlternatives(), "rule__Xmod_ExceptionKind__Alternatives");
			builder.put(grammarAccess.getSimulationAccess().getGroup(), "rule__Simulation__Group__0");
			builder.put(grammarAccess.getSimulationAccess().getGroup_11(), "rule__Simulation__Group_11__0");
			builder.put(grammarAccess.getSimulationAccess().getGroup_12(), "rule__Simulation__Group_12__0");
			builder.put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
			builder.put(grammarAccess.getComponentAccess().getGroup_10(), "rule__Component__Group_10__0");
			builder.put(grammarAccess.getComponentAccess().getGroup_11(), "rule__Component__Group_11__0");
			builder.put(grammarAccess.getViewAccess().getGroup(), "rule__View__Group__0");
			builder.put(grammarAccess.getViewAccess().getGroup_4(), "rule__View__Group_4__0");
			builder.put(grammarAccess.getViewAccess().getGroup_5(), "rule__View__Group_5__0");
			builder.put(grammarAccess.getViewAccess().getGroup_6(), "rule__View__Group_6__0");
			builder.put(grammarAccess.getViewAccess().getGroup_7(), "rule__View__Group_7__0");
			builder.put(grammarAccess.getViewAccess().getGroup_7_2(), "rule__View__Group_7_2__0");
			builder.put(grammarAccess.getIntBasicAccess().getGroup(), "rule__IntBasic__Group__0");
			builder.put(grammarAccess.getIntArrayAccess().getGroup(), "rule__IntArray__Group__0");
			builder.put(grammarAccess.getIntArrayAccess().getGroup_2(), "rule__IntArray__Group_2__0");
			builder.put(grammarAccess.getIntArrayAccess().getGroup_5(), "rule__IntArray__Group_5__0");
			builder.put(grammarAccess.getIntArrayAccess().getGroup_5_4(), "rule__IntArray__Group_5_4__0");
			builder.put(grammarAccess.getDoubleBasicAccess().getGroup(), "rule__DoubleBasic__Group__0");
			builder.put(grammarAccess.getDoubleArrayAccess().getGroup(), "rule__DoubleArray__Group__0");
			builder.put(grammarAccess.getDoubleArrayAccess().getGroup_2(), "rule__DoubleArray__Group_2__0");
			builder.put(grammarAccess.getDoubleArrayAccess().getGroup_5(), "rule__DoubleArray__Group_5__0");
			builder.put(grammarAccess.getDoubleArrayAccess().getGroup_5_4(), "rule__DoubleArray__Group_5_4__0");
			builder.put(grammarAccess.getStringBasicAccess().getGroup(), "rule__StringBasic__Group__0");
			builder.put(grammarAccess.getStringArrayAccess().getGroup(), "rule__StringArray__Group__0");
			builder.put(grammarAccess.getStringArrayAccess().getGroup_2(), "rule__StringArray__Group_2__0");
			builder.put(grammarAccess.getStringArrayAccess().getGroup_5(), "rule__StringArray__Group_5__0");
			builder.put(grammarAccess.getStringArrayAccess().getGroup_5_4(), "rule__StringArray__Group_5_4__0");
			builder.put(grammarAccess.getBooleanBasicAccess().getGroup(), "rule__BooleanBasic__Group__0");
			builder.put(grammarAccess.getBooleanArrayAccess().getGroup(), "rule__BooleanArray__Group__0");
			builder.put(grammarAccess.getBooleanArrayAccess().getGroup_2(), "rule__BooleanArray__Group_2__0");
			builder.put(grammarAccess.getBooleanArrayAccess().getGroup_5(), "rule__BooleanArray__Group_5__0");
			builder.put(grammarAccess.getBooleanArrayAccess().getGroup_5_4(), "rule__BooleanArray__Group_5_4__0");
			builder.put(grammarAccess.getXmod_ActionAccess().getGroup(), "rule__Xmod_Action__Group__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup(), "rule__Xmod_OperationDef__Group__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup_2(), "rule__Xmod_OperationDef__Group_2__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup_2_1(), "rule__Xmod_OperationDef__Group_2_1__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup_6(), "rule__Xmod_OperationDef__Group_6__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup_7(), "rule__Xmod_OperationDef__Group_7__0");
			builder.put(grammarAccess.getXmod_OperationCallAccess().getGroup(), "rule__Xmod_OperationCall__Group__0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getGroup(), "rule__Xmod_Exception__Group__0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getGroup_1_1(), "rule__Xmod_Exception__Group_1_1__0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getGroup_2(), "rule__Xmod_Exception__Group_2__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getSimulationAccess().getXmod_idAssignment_2(), "rule__Simulation__Xmod_idAssignment_2");
			builder.put(grammarAccess.getSimulationAccess().getStartTimeAssignment_4(), "rule__Simulation__StartTimeAssignment_4");
			builder.put(grammarAccess.getSimulationAccess().getEndTimeAssignment_6(), "rule__Simulation__EndTimeAssignment_6");
			builder.put(grammarAccess.getSimulationAccess().getDurationStepAssignment_8(), "rule__Simulation__DurationStepAssignment_8");
			builder.put(grammarAccess.getSimulationAccess().getComponentsAssignment_11_0(), "rule__Simulation__ComponentsAssignment_11_0");
			builder.put(grammarAccess.getSimulationAccess().getComponentsAssignment_11_1(), "rule__Simulation__ComponentsAssignment_11_1");
			builder.put(grammarAccess.getSimulationAccess().getViewsAssignment_12_0(), "rule__Simulation__ViewsAssignment_12_0");
			builder.put(grammarAccess.getSimulationAccess().getViewsAssignment_12_1(), "rule__Simulation__ViewsAssignment_12_1");
			builder.put(grammarAccess.getComponentAccess().getXmod_idAssignment_2(), "rule__Component__Xmod_idAssignment_2");
			builder.put(grammarAccess.getComponentAccess().getPriorityAssignment_4(), "rule__Component__PriorityAssignment_4");
			builder.put(grammarAccess.getComponentAccess().getPeriodAssignment_6(), "rule__Component__PeriodAssignment_6");
			builder.put(grammarAccess.getComponentAccess().getIsDataFlowAssignment_8(), "rule__Component__IsDataFlowAssignment_8");
			builder.put(grammarAccess.getComponentAccess().getAttributesAssignment_10_0(), "rule__Component__AttributesAssignment_10_0");
			builder.put(grammarAccess.getComponentAccess().getAttributesAssignment_10_1(), "rule__Component__AttributesAssignment_10_1");
			builder.put(grammarAccess.getComponentAccess().getActionsAssignment_11_0(), "rule__Component__ActionsAssignment_11_0");
			builder.put(grammarAccess.getComponentAccess().getActionsAssignment_11_1(), "rule__Component__ActionsAssignment_11_1");
			builder.put(grammarAccess.getViewAccess().getXmod_idAssignment_2(), "rule__View__Xmod_idAssignment_2");
			builder.put(grammarAccess.getViewAccess().getHostAssignment_4_1(), "rule__View__HostAssignment_4_1");
			builder.put(grammarAccess.getViewAccess().getPortAssignment_5_1(), "rule__View__PortAssignment_5_1");
			builder.put(grammarAccess.getViewAccess().getPeriodAssignment_6_1(), "rule__View__PeriodAssignment_6_1");
			builder.put(grammarAccess.getViewAccess().getObservedTagsAssignment_7_1(), "rule__View__ObservedTagsAssignment_7_1");
			builder.put(grammarAccess.getViewAccess().getObservedTagsAssignment_7_2_1(), "rule__View__ObservedTagsAssignment_7_2_1");
			builder.put(grammarAccess.getIntBasicAccess().getIsObservableAssignment_0(), "rule__IntBasic__IsObservableAssignment_0");
			builder.put(grammarAccess.getIntBasicAccess().getTypeAssignment_1(), "rule__IntBasic__TypeAssignment_1");
			builder.put(grammarAccess.getIntBasicAccess().getNameAssignment_2(), "rule__IntBasic__NameAssignment_2");
			builder.put(grammarAccess.getIntBasicAccess().getValueAssignment_4(), "rule__IntBasic__ValueAssignment_4");
			builder.put(grammarAccess.getIntArrayAccess().getIsObservableAssignment_0(), "rule__IntArray__IsObservableAssignment_0");
			builder.put(grammarAccess.getIntArrayAccess().getTypeAssignment_1(), "rule__IntArray__TypeAssignment_1");
			builder.put(grammarAccess.getIntArrayAccess().getMultiplicityAssignment_2_1(), "rule__IntArray__MultiplicityAssignment_2_1");
			builder.put(grammarAccess.getIntArrayAccess().getNameAssignment_3(), "rule__IntArray__NameAssignment_3");
			builder.put(grammarAccess.getIntArrayAccess().getValueAssignment_5_1(), "rule__IntArray__ValueAssignment_5_1");
			builder.put(grammarAccess.getIntArrayAccess().getValueAssignment_5_3(), "rule__IntArray__ValueAssignment_5_3");
			builder.put(grammarAccess.getIntArrayAccess().getValueAssignment_5_4_1(), "rule__IntArray__ValueAssignment_5_4_1");
			builder.put(grammarAccess.getDoubleBasicAccess().getIsObservableAssignment_0(), "rule__DoubleBasic__IsObservableAssignment_0");
			builder.put(grammarAccess.getDoubleBasicAccess().getTypeAssignment_1(), "rule__DoubleBasic__TypeAssignment_1");
			builder.put(grammarAccess.getDoubleBasicAccess().getNameAssignment_2(), "rule__DoubleBasic__NameAssignment_2");
			builder.put(grammarAccess.getDoubleBasicAccess().getValueAssignment_4(), "rule__DoubleBasic__ValueAssignment_4");
			builder.put(grammarAccess.getDoubleArrayAccess().getIsObservableAssignment_0(), "rule__DoubleArray__IsObservableAssignment_0");
			builder.put(grammarAccess.getDoubleArrayAccess().getTypeAssignment_1(), "rule__DoubleArray__TypeAssignment_1");
			builder.put(grammarAccess.getDoubleArrayAccess().getMultiplicityAssignment_2_1(), "rule__DoubleArray__MultiplicityAssignment_2_1");
			builder.put(grammarAccess.getDoubleArrayAccess().getNameAssignment_3(), "rule__DoubleArray__NameAssignment_3");
			builder.put(grammarAccess.getDoubleArrayAccess().getValueAssignment_5_1(), "rule__DoubleArray__ValueAssignment_5_1");
			builder.put(grammarAccess.getDoubleArrayAccess().getValueAssignment_5_3(), "rule__DoubleArray__ValueAssignment_5_3");
			builder.put(grammarAccess.getDoubleArrayAccess().getValueAssignment_5_4_1(), "rule__DoubleArray__ValueAssignment_5_4_1");
			builder.put(grammarAccess.getStringBasicAccess().getIsObservableAssignment_0(), "rule__StringBasic__IsObservableAssignment_0");
			builder.put(grammarAccess.getStringBasicAccess().getTypeAssignment_1(), "rule__StringBasic__TypeAssignment_1");
			builder.put(grammarAccess.getStringBasicAccess().getNameAssignment_2(), "rule__StringBasic__NameAssignment_2");
			builder.put(grammarAccess.getStringBasicAccess().getValueAssignment_4(), "rule__StringBasic__ValueAssignment_4");
			builder.put(grammarAccess.getStringArrayAccess().getIsObservableAssignment_0(), "rule__StringArray__IsObservableAssignment_0");
			builder.put(grammarAccess.getStringArrayAccess().getTypeAssignment_1(), "rule__StringArray__TypeAssignment_1");
			builder.put(grammarAccess.getStringArrayAccess().getMultiplicityAssignment_2_1(), "rule__StringArray__MultiplicityAssignment_2_1");
			builder.put(grammarAccess.getStringArrayAccess().getNameAssignment_3(), "rule__StringArray__NameAssignment_3");
			builder.put(grammarAccess.getStringArrayAccess().getValueAssignment_5_1(), "rule__StringArray__ValueAssignment_5_1");
			builder.put(grammarAccess.getStringArrayAccess().getValueAssignment_5_3(), "rule__StringArray__ValueAssignment_5_3");
			builder.put(grammarAccess.getStringArrayAccess().getValueAssignment_5_4_1(), "rule__StringArray__ValueAssignment_5_4_1");
			builder.put(grammarAccess.getBooleanBasicAccess().getIsObservableAssignment_0(), "rule__BooleanBasic__IsObservableAssignment_0");
			builder.put(grammarAccess.getBooleanBasicAccess().getTypeAssignment_1(), "rule__BooleanBasic__TypeAssignment_1");
			builder.put(grammarAccess.getBooleanBasicAccess().getNameAssignment_2(), "rule__BooleanBasic__NameAssignment_2");
			builder.put(grammarAccess.getBooleanBasicAccess().getValueAssignment_4(), "rule__BooleanBasic__ValueAssignment_4");
			builder.put(grammarAccess.getBooleanArrayAccess().getIsObservableAssignment_0(), "rule__BooleanArray__IsObservableAssignment_0");
			builder.put(grammarAccess.getBooleanArrayAccess().getTypeAssignment_1(), "rule__BooleanArray__TypeAssignment_1");
			builder.put(grammarAccess.getBooleanArrayAccess().getMultiplicityAssignment_2_1(), "rule__BooleanArray__MultiplicityAssignment_2_1");
			builder.put(grammarAccess.getBooleanArrayAccess().getNameAssignment_3(), "rule__BooleanArray__NameAssignment_3");
			builder.put(grammarAccess.getBooleanArrayAccess().getValueAssignment_5_1(), "rule__BooleanArray__ValueAssignment_5_1");
			builder.put(grammarAccess.getBooleanArrayAccess().getValueAssignment_5_3(), "rule__BooleanArray__ValueAssignment_5_3");
			builder.put(grammarAccess.getBooleanArrayAccess().getValueAssignment_5_4_1(), "rule__BooleanArray__ValueAssignment_5_4_1");
			builder.put(grammarAccess.getXmod_ActionAccess().getNameAssignment_1(), "rule__Xmod_Action__NameAssignment_1");
			builder.put(grammarAccess.getXmod_ActionAccess().getOperationsAssignment_3(), "rule__Xmod_Action__OperationsAssignment_3");
			builder.put(grammarAccess.getXmod_ActionAccess().getOperationsAssignment_4(), "rule__Xmod_Action__OperationsAssignment_4");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getNameAssignment_0(), "rule__Xmod_OperationDef__NameAssignment_0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getParametersTagAssignment_2_0(), "rule__Xmod_OperationDef__ParametersTagAssignment_2_0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getParametersTagAssignment_2_1_1(), "rule__Xmod_OperationDef__ParametersTagAssignment_2_1_1");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getObjectTagAssignment_5(), "rule__Xmod_OperationDef__ObjectTagAssignment_5");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getReturnTagAssignment_6_1(), "rule__Xmod_OperationDef__ReturnTagAssignment_6_1");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getExceptionsAssignment_7_0(), "rule__Xmod_OperationDef__ExceptionsAssignment_7_0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getExceptionsAssignment_7_1(), "rule__Xmod_OperationDef__ExceptionsAssignment_7_1");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getKindAssignment_1_0(), "rule__Xmod_Exception__KindAssignment_1_0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getKindAssignment_1_1_0(), "rule__Xmod_Exception__KindAssignment_1_1_0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getFilterAssignment_1_1_2(), "rule__Xmod_Exception__FilterAssignment_1_1_2");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getCalledOperationAssignment_2_1(), "rule__Xmod_Exception__CalledOperationAssignment_2_1");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getReactionAssignment_4(), "rule__Xmod_Exception__ReactionAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SpiceGrammarAccess grammarAccess;

	@Override
	protected InternalSpiceParser createParser() {
		InternalSpiceParser result = new InternalSpiceParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SpiceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SpiceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
