/**
 * generated by Xtext 2.40.0
 */
package org.xtext.formatting2;

import Spice.Xmod_Action;
import Spice.Xmod_Exception;
import Spice.Xmod_Operation;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.services.SpiceGrammarAccess;

@SuppressWarnings("all")
public class SpiceFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SpiceGrammarAccess _spiceGrammarAccess;

  protected void _format(final Xmod_Action xmod_Action, @Extension final IFormattableDocument document) {
    EList<Xmod_Operation> _operations = xmod_Action.getOperations();
    for (final Xmod_Operation xmod_Operation : _operations) {
      document.<Xmod_Operation>format(xmod_Operation);
    }
  }

  protected void _format(final Xmod_Operation xmod_Operation, @Extension final IFormattableDocument document) {
    EList<Xmod_Exception> _exceptions = xmod_Operation.getExceptions();
    for (final Xmod_Exception xmod_Exception : _exceptions) {
      document.<Xmod_Exception>format(xmod_Exception);
    }
  }

  @XbaseGenerated
  public void format(final Object xmod_Action, final IFormattableDocument document) {
    if (xmod_Action instanceof XtextResource) {
      _format((XtextResource)xmod_Action, document);
      return;
    } else if (xmod_Action instanceof Xmod_Action) {
      _format((Xmod_Action)xmod_Action, document);
      return;
    } else if (xmod_Action instanceof Xmod_Operation) {
      _format((Xmod_Operation)xmod_Action, document);
      return;
    } else if (xmod_Action instanceof EObject) {
      _format((EObject)xmod_Action, document);
      return;
    } else if (xmod_Action == null) {
      _format((Void)null, document);
      return;
    } else if (xmod_Action != null) {
      _format(xmod_Action, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(xmod_Action, document).toString());
    }
  }
}
