/*
 * generated by Xtext 2.40.0
 */
package org.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SpiceStandaloneSetup extends SpiceStandaloneSetupGenerated {

	public static void doSetup() {
		new SpiceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
