/*
 * generated by Xtext 2.40.0
 */
package org.xtext;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.xtext.scoping.SpiceScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpiceRuntimeModule extends AbstractSpiceRuntimeModule {
	
	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
	    return SpiceQualifiedNameProvider.class;
	}
	
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
	    return SpiceScopeProvider.class;
	}
}
