/*
 * generated by Xtext 2.40.0
 */
package org.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SpiceGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SimulationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Simulation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSimulationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cXmod_idKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXmod_idAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXmod_idEStringParserRuleCall_2_0 = (RuleCall)cXmod_idAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStartTimeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStartTimeELongParserRuleCall_4_0 = (RuleCall)cStartTimeAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEndTimeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEndTimeELongParserRuleCall_6_0 = (RuleCall)cEndTimeAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDurationStepAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDurationStepELongParserRuleCall_8_0 = (RuleCall)cDurationStepAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cComponentsAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final RuleCall cComponentsComponentParserRuleCall_11_0_0 = (RuleCall)cComponentsAssignment_11_0.eContents().get(0);
		private final Assignment cComponentsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cComponentsComponentParserRuleCall_11_1_0 = (RuleCall)cComponentsAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Assignment cViewsAssignment_12_0 = (Assignment)cGroup_12.eContents().get(0);
		private final RuleCall cViewsViewParserRuleCall_12_0_0 = (RuleCall)cViewsAssignment_12_0.eContents().get(0);
		private final Assignment cViewsAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cViewsViewParserRuleCall_12_1_0 = (RuleCall)cViewsAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Simulation returns Simulation:
		//    'Simulation' 'xmod_id:' xmod_id=EString '('startTime=ELong',' endTime=ELong',' durationStep=ELong')' '{'
		//        ( components+=Component (components+=Component)* )?
		//        ( views+=View (views+=View)* )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Simulation' 'xmod_id:' xmod_id=EString '('startTime=ELong',' endTime=ELong',' durationStep=ELong')' '{'
		//    ( components+=Component (components+=Component)* )?
		//    ( views+=View (views+=View)* )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Simulation'
		public Keyword getSimulationKeyword_0() { return cSimulationKeyword_0; }
		
		//'xmod_id:'
		public Keyword getXmod_idKeyword_1() { return cXmod_idKeyword_1; }
		
		//xmod_id=EString
		public Assignment getXmod_idAssignment_2() { return cXmod_idAssignment_2; }
		
		//EString
		public RuleCall getXmod_idEStringParserRuleCall_2_0() { return cXmod_idEStringParserRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//startTime=ELong
		public Assignment getStartTimeAssignment_4() { return cStartTimeAssignment_4; }
		
		//ELong
		public RuleCall getStartTimeELongParserRuleCall_4_0() { return cStartTimeELongParserRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//endTime=ELong
		public Assignment getEndTimeAssignment_6() { return cEndTimeAssignment_6; }
		
		//ELong
		public RuleCall getEndTimeELongParserRuleCall_6_0() { return cEndTimeELongParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//durationStep=ELong
		public Assignment getDurationStepAssignment_8() { return cDurationStepAssignment_8; }
		
		//ELong
		public RuleCall getDurationStepELongParserRuleCall_8_0() { return cDurationStepELongParserRuleCall_8_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//( components+=Component (components+=Component)* )?
		public Group getGroup_11() { return cGroup_11; }
		
		//components+=Component
		public Assignment getComponentsAssignment_11_0() { return cComponentsAssignment_11_0; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_11_0_0() { return cComponentsComponentParserRuleCall_11_0_0; }
		
		//(components+=Component)*
		public Assignment getComponentsAssignment_11_1() { return cComponentsAssignment_11_1; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_11_1_0() { return cComponentsComponentParserRuleCall_11_1_0; }
		
		//( views+=View (views+=View)* )?
		public Group getGroup_12() { return cGroup_12; }
		
		//views+=View
		public Assignment getViewsAssignment_12_0() { return cViewsAssignment_12_0; }
		
		//View
		public RuleCall getViewsViewParserRuleCall_12_0_0() { return cViewsViewParserRuleCall_12_0_0; }
		
		//(views+=View)*
		public Assignment getViewsAssignment_12_1() { return cViewsAssignment_12_1; }
		
		//View
		public RuleCall getViewsViewParserRuleCall_12_1_0() { return cViewsViewParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cXmod_idKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXmod_idAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXmod_idEStringParserRuleCall_2_0 = (RuleCall)cXmod_idAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPriorityAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPriorityELongParserRuleCall_4_0 = (RuleCall)cPriorityAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPeriodAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPeriodELongParserRuleCall_6_0 = (RuleCall)cPeriodAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cIsDataFlowAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final Keyword cIsDataFlowDFKeyword_8_0 = (Keyword)cIsDataFlowAssignment_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Assignment cAttributesAssignment_10_0 = (Assignment)cGroup_10.eContents().get(0);
		private final RuleCall cAttributesAttributeParserRuleCall_10_0_0 = (RuleCall)cAttributesAssignment_10_0.eContents().get(0);
		private final Assignment cAttributesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cAttributesAttributeParserRuleCall_10_1_0 = (RuleCall)cAttributesAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cActionsAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final RuleCall cActionsXmod_ActionParserRuleCall_11_0_0 = (RuleCall)cActionsAssignment_11_0.eContents().get(0);
		private final Assignment cActionsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cActionsXmod_ActionParserRuleCall_11_1_0 = (RuleCall)cActionsAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Component returns Component:
		//    'Component' 'xmod_id:' xmod_id=EString '('priority=ELong',' period=ELong')' (isDataFlow?='DF')? '{'
		//        ( attributes+=Attribute ( attributes+=Attribute )* )?
		//        ( actions+=Xmod_Action ( actions+=Xmod_Action )* )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Component' 'xmod_id:' xmod_id=EString '('priority=ELong',' period=ELong')' (isDataFlow?='DF')? '{'
		//    ( attributes+=Attribute ( attributes+=Attribute )* )?
		//    ( actions+=Xmod_Action ( actions+=Xmod_Action )* )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Component'
		public Keyword getComponentKeyword_0() { return cComponentKeyword_0; }
		
		//'xmod_id:'
		public Keyword getXmod_idKeyword_1() { return cXmod_idKeyword_1; }
		
		//xmod_id=EString
		public Assignment getXmod_idAssignment_2() { return cXmod_idAssignment_2; }
		
		//EString
		public RuleCall getXmod_idEStringParserRuleCall_2_0() { return cXmod_idEStringParserRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//priority=ELong
		public Assignment getPriorityAssignment_4() { return cPriorityAssignment_4; }
		
		//ELong
		public RuleCall getPriorityELongParserRuleCall_4_0() { return cPriorityELongParserRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//period=ELong
		public Assignment getPeriodAssignment_6() { return cPeriodAssignment_6; }
		
		//ELong
		public RuleCall getPeriodELongParserRuleCall_6_0() { return cPeriodELongParserRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//(isDataFlow?='DF')?
		public Assignment getIsDataFlowAssignment_8() { return cIsDataFlowAssignment_8; }
		
		//'DF'
		public Keyword getIsDataFlowDFKeyword_8_0() { return cIsDataFlowDFKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//( attributes+=Attribute ( attributes+=Attribute )* )?
		public Group getGroup_10() { return cGroup_10; }
		
		//attributes+=Attribute
		public Assignment getAttributesAssignment_10_0() { return cAttributesAssignment_10_0; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_10_0_0() { return cAttributesAttributeParserRuleCall_10_0_0; }
		
		//( attributes+=Attribute )*
		public Assignment getAttributesAssignment_10_1() { return cAttributesAssignment_10_1; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_10_1_0() { return cAttributesAttributeParserRuleCall_10_1_0; }
		
		//( actions+=Xmod_Action ( actions+=Xmod_Action )* )?
		public Group getGroup_11() { return cGroup_11; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_11_0() { return cActionsAssignment_11_0; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_11_0_0() { return cActionsXmod_ActionParserRuleCall_11_0_0; }
		
		//( actions+=Xmod_Action )*
		public Assignment getActionsAssignment_11_1() { return cActionsAssignment_11_1; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_11_1_0() { return cActionsXmod_ActionParserRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class ViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.View");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cViewKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cXmod_idKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXmod_idAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXmod_idEStringParserRuleCall_2_0 = (RuleCall)cXmod_idAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cHostKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cHostAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cHostEStringParserRuleCall_4_1_0 = (RuleCall)cHostAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPortKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPortAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPortEIntParserRuleCall_5_1_0 = (RuleCall)cPortAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPeriodKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPeriodAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPeriodELongParserRuleCall_6_1_0 = (RuleCall)cPeriodAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cObserveKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cObservedTagsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cObservedTagsEStringParserRuleCall_7_1_0 = (RuleCall)cObservedTagsAssignment_7_1.eContents().get(0);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cCommaKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cObservedTagsAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final RuleCall cObservedTagsEStringParserRuleCall_7_2_1_0 = (RuleCall)cObservedTagsAssignment_7_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//View returns View:
		//    'View' 'xmod_id:' xmod_id=EString '{'
		//        ( 'host' host=EString )?
		//        ( 'port' port=EInt )?
		//        ( 'period' period=ELong )?
		//        ( 'observe' observedTags+=EString ( ',' observedTags+=EString )* ';' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'View' 'xmod_id:' xmod_id=EString '{'
		//    ( 'host' host=EString )?
		//    ( 'port' port=EInt )?
		//    ( 'period' period=ELong )?
		//    ( 'observe' observedTags+=EString ( ',' observedTags+=EString )* ';' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'View'
		public Keyword getViewKeyword_0() { return cViewKeyword_0; }
		
		//'xmod_id:'
		public Keyword getXmod_idKeyword_1() { return cXmod_idKeyword_1; }
		
		//xmod_id=EString
		public Assignment getXmod_idAssignment_2() { return cXmod_idAssignment_2; }
		
		//EString
		public RuleCall getXmod_idEStringParserRuleCall_2_0() { return cXmod_idEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//( 'host' host=EString )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'host'
		public Keyword getHostKeyword_4_0() { return cHostKeyword_4_0; }
		
		//host=EString
		public Assignment getHostAssignment_4_1() { return cHostAssignment_4_1; }
		
		//EString
		public RuleCall getHostEStringParserRuleCall_4_1_0() { return cHostEStringParserRuleCall_4_1_0; }
		
		//( 'port' port=EInt )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'port'
		public Keyword getPortKeyword_5_0() { return cPortKeyword_5_0; }
		
		//port=EInt
		public Assignment getPortAssignment_5_1() { return cPortAssignment_5_1; }
		
		//EInt
		public RuleCall getPortEIntParserRuleCall_5_1_0() { return cPortEIntParserRuleCall_5_1_0; }
		
		//( 'period' period=ELong )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'period'
		public Keyword getPeriodKeyword_6_0() { return cPeriodKeyword_6_0; }
		
		//period=ELong
		public Assignment getPeriodAssignment_6_1() { return cPeriodAssignment_6_1; }
		
		//ELong
		public RuleCall getPeriodELongParserRuleCall_6_1_0() { return cPeriodELongParserRuleCall_6_1_0; }
		
		//( 'observe' observedTags+=EString ( ',' observedTags+=EString )* ';' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'observe'
		public Keyword getObserveKeyword_7_0() { return cObserveKeyword_7_0; }
		
		//observedTags+=EString
		public Assignment getObservedTagsAssignment_7_1() { return cObservedTagsAssignment_7_1; }
		
		//EString
		public RuleCall getObservedTagsEStringParserRuleCall_7_1_0() { return cObservedTagsEStringParserRuleCall_7_1_0; }
		
		//( ',' observedTags+=EString )*
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//','
		public Keyword getCommaKeyword_7_2_0() { return cCommaKeyword_7_2_0; }
		
		//observedTags+=EString
		public Assignment getObservedTagsAssignment_7_2_1() { return cObservedTagsAssignment_7_2_1; }
		
		//EString
		public RuleCall getObservedTagsEStringParserRuleCall_7_2_1_0() { return cObservedTagsEStringParserRuleCall_7_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_7_3() { return cSemicolonKeyword_7_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Attribute");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntBasicParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntArrayParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDoubleBasicParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDoubleArrayParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cStringBasicParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cStringArrayParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cBooleanBasicParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cBooleanArrayParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Attribute returns Attribute:
		//    IntBasic | IntArray |
		//    DoubleBasic | DoubleArray |
		//    StringBasic | StringArray |
		//    BooleanBasic | BooleanArray;
		@Override public ParserRule getRule() { return rule; }
		
		//IntBasic | IntArray |
		//DoubleBasic | DoubleArray |
		//StringBasic | StringArray |
		//BooleanBasic | BooleanArray
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntBasic
		public RuleCall getIntBasicParserRuleCall_0() { return cIntBasicParserRuleCall_0; }
		
		//IntArray
		public RuleCall getIntArrayParserRuleCall_1() { return cIntArrayParserRuleCall_1; }
		
		//DoubleBasic
		public RuleCall getDoubleBasicParserRuleCall_2() { return cDoubleBasicParserRuleCall_2; }
		
		//DoubleArray
		public RuleCall getDoubleArrayParserRuleCall_3() { return cDoubleArrayParserRuleCall_3; }
		
		//StringBasic
		public RuleCall getStringBasicParserRuleCall_4() { return cStringBasicParserRuleCall_4; }
		
		//StringArray
		public RuleCall getStringArrayParserRuleCall_5() { return cStringArrayParserRuleCall_5; }
		
		//BooleanBasic
		public RuleCall getBooleanBasicParserRuleCall_6() { return cBooleanBasicParserRuleCall_6; }
		
		//BooleanArray
		public RuleCall getBooleanArrayParserRuleCall_7() { return cBooleanArrayParserRuleCall_7; }
	}
	public class IntBasicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.IntBasic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsObservableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsObservableObservableKeyword_0_0 = (Keyword)cIsObservableAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEIntParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//IntBasic returns BasicAttribute:
		//    (isObservable?='observable')? type=EString name=EString '=' value=EInt ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(isObservable?='observable')? type=EString name=EString '=' value=EInt ';'
		public Group getGroup() { return cGroup; }
		
		//(isObservable?='observable')?
		public Assignment getIsObservableAssignment_0() { return cIsObservableAssignment_0; }
		
		//'observable'
		public Keyword getIsObservableObservableKeyword_0_0() { return cIsObservableObservableKeyword_0_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//value=EInt
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_4_0() { return cValueEIntParserRuleCall_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}
	public class IntArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.IntArray");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsObservableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsObservableObservableKeyword_0_0 = (Keyword)cIsObservableAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMultiplicityAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMultiplicityELongParserRuleCall_2_1_0 = (RuleCall)cMultiplicityAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueEIntParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Keyword cCommaKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cValueAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cValueEIntParserRuleCall_5_3_0 = (RuleCall)cValueAssignment_5_3.eContents().get(0);
		private final Group cGroup_5_4 = (Group)cGroup_5.eContents().get(4);
		private final Keyword cCommaKeyword_5_4_0 = (Keyword)cGroup_5_4.eContents().get(0);
		private final Assignment cValueAssignment_5_4_1 = (Assignment)cGroup_5_4.eContents().get(1);
		private final RuleCall cValueEIntParserRuleCall_5_4_1_0 = (RuleCall)cValueAssignment_5_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//IntArray returns ArrayAttribute:
		//    (isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EInt ',' value+=EInt ( ',' value+=EInt )*')') ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EInt ',' value+=EInt ( ',' value+=EInt )*')') ';'
		public Group getGroup() { return cGroup; }
		
		//(isObservable?='observable')?
		public Assignment getIsObservableAssignment_0() { return cIsObservableAssignment_0; }
		
		//'observable'
		public Keyword getIsObservableObservableKeyword_0_0() { return cIsObservableObservableKeyword_0_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//('['multiplicity=ELong']')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }
		
		//multiplicity=ELong
		public Assignment getMultiplicityAssignment_2_1() { return cMultiplicityAssignment_2_1; }
		
		//ELong
		public RuleCall getMultiplicityELongParserRuleCall_2_1_0() { return cMultiplicityELongParserRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//('('value+=EInt ',' value+=EInt ( ',' value+=EInt )*')')
		public Group getGroup_5() { return cGroup_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_0() { return cLeftParenthesisKeyword_5_0; }
		
		//value+=EInt
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_5_1_0() { return cValueEIntParserRuleCall_5_1_0; }
		
		//','
		public Keyword getCommaKeyword_5_2() { return cCommaKeyword_5_2; }
		
		//value+=EInt
		public Assignment getValueAssignment_5_3() { return cValueAssignment_5_3; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_5_3_0() { return cValueEIntParserRuleCall_5_3_0; }
		
		//( ',' value+=EInt )*
		public Group getGroup_5_4() { return cGroup_5_4; }
		
		//','
		public Keyword getCommaKeyword_5_4_0() { return cCommaKeyword_5_4_0; }
		
		//value+=EInt
		public Assignment getValueAssignment_5_4_1() { return cValueAssignment_5_4_1; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_5_4_1_0() { return cValueEIntParserRuleCall_5_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_5() { return cRightParenthesisKeyword_5_5; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	public class DoubleBasicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.DoubleBasic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsObservableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsObservableObservableKeyword_0_0 = (Keyword)cIsObservableAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEDoubleParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//DoubleBasic returns BasicAttribute:
		//    (isObservable?='observable')? type=EString name=EString '=' value=EDouble ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(isObservable?='observable')? type=EString name=EString '=' value=EDouble ';'
		public Group getGroup() { return cGroup; }
		
		//(isObservable?='observable')?
		public Assignment getIsObservableAssignment_0() { return cIsObservableAssignment_0; }
		
		//'observable'
		public Keyword getIsObservableObservableKeyword_0_0() { return cIsObservableObservableKeyword_0_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//value=EDouble
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_4_0() { return cValueEDoubleParserRuleCall_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}
	public class DoubleArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.DoubleArray");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsObservableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsObservableObservableKeyword_0_0 = (Keyword)cIsObservableAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMultiplicityAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMultiplicityELongParserRuleCall_2_1_0 = (RuleCall)cMultiplicityAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueEDoubleParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Keyword cCommaKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cValueAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cValueEDoubleParserRuleCall_5_3_0 = (RuleCall)cValueAssignment_5_3.eContents().get(0);
		private final Group cGroup_5_4 = (Group)cGroup_5.eContents().get(4);
		private final Keyword cCommaKeyword_5_4_0 = (Keyword)cGroup_5_4.eContents().get(0);
		private final Assignment cValueAssignment_5_4_1 = (Assignment)cGroup_5_4.eContents().get(1);
		private final RuleCall cValueEDoubleParserRuleCall_5_4_1_0 = (RuleCall)cValueAssignment_5_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//DoubleArray returns ArrayAttribute:
		//    (isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EDouble ',' value+=EDouble ( ',' value+=EDouble )*')') ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EDouble ',' value+=EDouble ( ',' value+=EDouble )*')') ';'
		public Group getGroup() { return cGroup; }
		
		//(isObservable?='observable')?
		public Assignment getIsObservableAssignment_0() { return cIsObservableAssignment_0; }
		
		//'observable'
		public Keyword getIsObservableObservableKeyword_0_0() { return cIsObservableObservableKeyword_0_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//('['multiplicity=ELong']')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }
		
		//multiplicity=ELong
		public Assignment getMultiplicityAssignment_2_1() { return cMultiplicityAssignment_2_1; }
		
		//ELong
		public RuleCall getMultiplicityELongParserRuleCall_2_1_0() { return cMultiplicityELongParserRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//('('value+=EDouble ',' value+=EDouble ( ',' value+=EDouble )*')')
		public Group getGroup_5() { return cGroup_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_0() { return cLeftParenthesisKeyword_5_0; }
		
		//value+=EDouble
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_5_1_0() { return cValueEDoubleParserRuleCall_5_1_0; }
		
		//','
		public Keyword getCommaKeyword_5_2() { return cCommaKeyword_5_2; }
		
		//value+=EDouble
		public Assignment getValueAssignment_5_3() { return cValueAssignment_5_3; }
		
		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_5_3_0() { return cValueEDoubleParserRuleCall_5_3_0; }
		
		//( ',' value+=EDouble )*
		public Group getGroup_5_4() { return cGroup_5_4; }
		
		//','
		public Keyword getCommaKeyword_5_4_0() { return cCommaKeyword_5_4_0; }
		
		//value+=EDouble
		public Assignment getValueAssignment_5_4_1() { return cValueAssignment_5_4_1; }
		
		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_5_4_1_0() { return cValueEDoubleParserRuleCall_5_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_5() { return cRightParenthesisKeyword_5_5; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	public class StringBasicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.StringBasic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsObservableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsObservableObservableKeyword_0_0 = (Keyword)cIsObservableAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//StringBasic returns BasicAttribute:
		//    (isObservable?='observable')? type=EString name=EString '=' value=EString ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(isObservable?='observable')? type=EString name=EString '=' value=EString ';'
		public Group getGroup() { return cGroup; }
		
		//(isObservable?='observable')?
		public Assignment getIsObservableAssignment_0() { return cIsObservableAssignment_0; }
		
		//'observable'
		public Keyword getIsObservableObservableKeyword_0_0() { return cIsObservableObservableKeyword_0_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}
	public class StringArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.StringArray");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsObservableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsObservableObservableKeyword_0_0 = (Keyword)cIsObservableAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMultiplicityAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMultiplicityELongParserRuleCall_2_1_0 = (RuleCall)cMultiplicityAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Keyword cCommaKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cValueAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cValueEStringParserRuleCall_5_3_0 = (RuleCall)cValueAssignment_5_3.eContents().get(0);
		private final Group cGroup_5_4 = (Group)cGroup_5.eContents().get(4);
		private final Keyword cCommaKeyword_5_4_0 = (Keyword)cGroup_5_4.eContents().get(0);
		private final Assignment cValueAssignment_5_4_1 = (Assignment)cGroup_5_4.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_5_4_1_0 = (RuleCall)cValueAssignment_5_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StringArray returns ArrayAttribute:
		//    (isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EString ',' value+=EString ( ',' value+=EString )*')') ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EString ',' value+=EString ( ',' value+=EString )*')') ';'
		public Group getGroup() { return cGroup; }
		
		//(isObservable?='observable')?
		public Assignment getIsObservableAssignment_0() { return cIsObservableAssignment_0; }
		
		//'observable'
		public Keyword getIsObservableObservableKeyword_0_0() { return cIsObservableObservableKeyword_0_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//('['multiplicity=ELong']')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }
		
		//multiplicity=ELong
		public Assignment getMultiplicityAssignment_2_1() { return cMultiplicityAssignment_2_1; }
		
		//ELong
		public RuleCall getMultiplicityELongParserRuleCall_2_1_0() { return cMultiplicityELongParserRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//('('value+=EString ',' value+=EString ( ',' value+=EString )*')')
		public Group getGroup_5() { return cGroup_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_0() { return cLeftParenthesisKeyword_5_0; }
		
		//value+=EString
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_5_1_0() { return cValueEStringParserRuleCall_5_1_0; }
		
		//','
		public Keyword getCommaKeyword_5_2() { return cCommaKeyword_5_2; }
		
		//value+=EString
		public Assignment getValueAssignment_5_3() { return cValueAssignment_5_3; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_5_3_0() { return cValueEStringParserRuleCall_5_3_0; }
		
		//( ',' value+=EString )*
		public Group getGroup_5_4() { return cGroup_5_4; }
		
		//','
		public Keyword getCommaKeyword_5_4_0() { return cCommaKeyword_5_4_0; }
		
		//value+=EString
		public Assignment getValueAssignment_5_4_1() { return cValueAssignment_5_4_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_5_4_1_0() { return cValueEStringParserRuleCall_5_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_5() { return cRightParenthesisKeyword_5_5; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	public class BooleanBasicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.BooleanBasic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsObservableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsObservableObservableKeyword_0_0 = (Keyword)cIsObservableAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEBooleanParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//BooleanBasic returns BasicAttribute:
		//    (isObservable?='observable')? type=EString name=EString '=' value=EBoolean ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(isObservable?='observable')? type=EString name=EString '=' value=EBoolean ';'
		public Group getGroup() { return cGroup; }
		
		//(isObservable?='observable')?
		public Assignment getIsObservableAssignment_0() { return cIsObservableAssignment_0; }
		
		//'observable'
		public Keyword getIsObservableObservableKeyword_0_0() { return cIsObservableObservableKeyword_0_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//value=EBoolean
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//EBoolean
		public RuleCall getValueEBooleanParserRuleCall_4_0() { return cValueEBooleanParserRuleCall_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}
	public class BooleanArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.BooleanArray");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsObservableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsObservableObservableKeyword_0_0 = (Keyword)cIsObservableAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMultiplicityAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMultiplicityELongParserRuleCall_2_1_0 = (RuleCall)cMultiplicityAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueEBooleanParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Keyword cCommaKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cValueAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cValueEBooleanParserRuleCall_5_3_0 = (RuleCall)cValueAssignment_5_3.eContents().get(0);
		private final Group cGroup_5_4 = (Group)cGroup_5.eContents().get(4);
		private final Keyword cCommaKeyword_5_4_0 = (Keyword)cGroup_5_4.eContents().get(0);
		private final Assignment cValueAssignment_5_4_1 = (Assignment)cGroup_5_4.eContents().get(1);
		private final RuleCall cValueEBooleanParserRuleCall_5_4_1_0 = (RuleCall)cValueAssignment_5_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//BooleanArray returns ArrayAttribute:
		//    (isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EBoolean ',' value+=EBoolean ( ',' value+=EBoolean )*')') ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EBoolean ',' value+=EBoolean ( ',' value+=EBoolean )*')') ';'
		public Group getGroup() { return cGroup; }
		
		//(isObservable?='observable')?
		public Assignment getIsObservableAssignment_0() { return cIsObservableAssignment_0; }
		
		//'observable'
		public Keyword getIsObservableObservableKeyword_0_0() { return cIsObservableObservableKeyword_0_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//('['multiplicity=ELong']')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }
		
		//multiplicity=ELong
		public Assignment getMultiplicityAssignment_2_1() { return cMultiplicityAssignment_2_1; }
		
		//ELong
		public RuleCall getMultiplicityELongParserRuleCall_2_1_0() { return cMultiplicityELongParserRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//('('value+=EBoolean ',' value+=EBoolean ( ',' value+=EBoolean )*')')
		public Group getGroup_5() { return cGroup_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_0() { return cLeftParenthesisKeyword_5_0; }
		
		//value+=EBoolean
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//EBoolean
		public RuleCall getValueEBooleanParserRuleCall_5_1_0() { return cValueEBooleanParserRuleCall_5_1_0; }
		
		//','
		public Keyword getCommaKeyword_5_2() { return cCommaKeyword_5_2; }
		
		//value+=EBoolean
		public Assignment getValueAssignment_5_3() { return cValueAssignment_5_3; }
		
		//EBoolean
		public RuleCall getValueEBooleanParserRuleCall_5_3_0() { return cValueEBooleanParserRuleCall_5_3_0; }
		
		//( ',' value+=EBoolean )*
		public Group getGroup_5_4() { return cGroup_5_4; }
		
		//','
		public Keyword getCommaKeyword_5_4_0() { return cCommaKeyword_5_4_0; }
		
		//value+=EBoolean
		public Assignment getValueAssignment_5_4_1() { return cValueAssignment_5_4_1; }
		
		//EBoolean
		public RuleCall getValueEBooleanParserRuleCall_5_4_1_0() { return cValueEBooleanParserRuleCall_5_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_5() { return cRightParenthesisKeyword_5_5; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	public class Xmod_ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Xmod_Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperationsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperationsXmod_OperationCallParserRuleCall_3_0 = (RuleCall)cOperationsAssignment_3.eContents().get(0);
		private final Assignment cOperationsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperationsXmod_OperationCallParserRuleCall_4_0 = (RuleCall)cOperationsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Xmod_Action returns Xmod_Action:
		//    'Action' name=EString '{' operations+=Xmod_OperationCall (operations+=Xmod_OperationCall)* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Action' name=EString '{' operations+=Xmod_OperationCall (operations+=Xmod_OperationCall)* '}'
		public Group getGroup() { return cGroup; }
		
		//'Action'
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//operations+=Xmod_OperationCall
		public Assignment getOperationsAssignment_3() { return cOperationsAssignment_3; }
		
		//Xmod_OperationCall
		public RuleCall getOperationsXmod_OperationCallParserRuleCall_3_0() { return cOperationsXmod_OperationCallParserRuleCall_3_0; }
		
		//(operations+=Xmod_OperationCall)*
		public Assignment getOperationsAssignment_4() { return cOperationsAssignment_4; }
		
		//Xmod_OperationCall
		public RuleCall getOperationsXmod_OperationCallParserRuleCall_4_0() { return cOperationsXmod_OperationCallParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class Xmod_OperationDefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Xmod_OperationDef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cParametersTagAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cParametersTagEStringParserRuleCall_2_0_0 = (RuleCall)cParametersTagAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cParametersTagAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cParametersTagEStringParserRuleCall_2_1_1_0 = (RuleCall)cParametersTagAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cOnKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cObjectTagAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cObjectTagEStringParserRuleCall_5_0 = (RuleCall)cObjectTagAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cReturnsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cReturnTagAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cReturnTagEStringParserRuleCall_6_1_0 = (RuleCall)cReturnTagAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cExceptionsAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cExceptionsXmod_ExceptionParserRuleCall_7_0_0 = (RuleCall)cExceptionsAssignment_7_0.eContents().get(0);
		private final Assignment cExceptionsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cExceptionsXmod_ExceptionParserRuleCall_7_1_0 = (RuleCall)cExceptionsAssignment_7_1.eContents().get(0);
		
		//Xmod_OperationDef returns Xmod_Operation:
		//    name=EString'('( parametersTag+=EString ( "," parametersTag+=EString )* )?')'
		//        'on' objectTag=EString ('returns' returnTag=EString)?
		//        (exceptions+=Xmod_Exception (exceptions+=Xmod_Exception)* )?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString'('( parametersTag+=EString ( "," parametersTag+=EString )* )?')'
		//    'on' objectTag=EString ('returns' returnTag=EString)?
		//    (exceptions+=Xmod_Exception (exceptions+=Xmod_Exception)* )?
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//( parametersTag+=EString ( "," parametersTag+=EString )* )?
		public Group getGroup_2() { return cGroup_2; }
		
		//parametersTag+=EString
		public Assignment getParametersTagAssignment_2_0() { return cParametersTagAssignment_2_0; }
		
		//EString
		public RuleCall getParametersTagEStringParserRuleCall_2_0_0() { return cParametersTagEStringParserRuleCall_2_0_0; }
		
		//( "," parametersTag+=EString )*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }
		
		//parametersTag+=EString
		public Assignment getParametersTagAssignment_2_1_1() { return cParametersTagAssignment_2_1_1; }
		
		//EString
		public RuleCall getParametersTagEStringParserRuleCall_2_1_1_0() { return cParametersTagEStringParserRuleCall_2_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'on'
		public Keyword getOnKeyword_4() { return cOnKeyword_4; }
		
		//objectTag=EString
		public Assignment getObjectTagAssignment_5() { return cObjectTagAssignment_5; }
		
		//EString
		public RuleCall getObjectTagEStringParserRuleCall_5_0() { return cObjectTagEStringParserRuleCall_5_0; }
		
		//('returns' returnTag=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'returns'
		public Keyword getReturnsKeyword_6_0() { return cReturnsKeyword_6_0; }
		
		//returnTag=EString
		public Assignment getReturnTagAssignment_6_1() { return cReturnTagAssignment_6_1; }
		
		//EString
		public RuleCall getReturnTagEStringParserRuleCall_6_1_0() { return cReturnTagEStringParserRuleCall_6_1_0; }
		
		//(exceptions+=Xmod_Exception (exceptions+=Xmod_Exception)* )?
		public Group getGroup_7() { return cGroup_7; }
		
		//exceptions+=Xmod_Exception
		public Assignment getExceptionsAssignment_7_0() { return cExceptionsAssignment_7_0; }
		
		//Xmod_Exception
		public RuleCall getExceptionsXmod_ExceptionParserRuleCall_7_0_0() { return cExceptionsXmod_ExceptionParserRuleCall_7_0_0; }
		
		//(exceptions+=Xmod_Exception)*
		public Assignment getExceptionsAssignment_7_1() { return cExceptionsAssignment_7_1; }
		
		//Xmod_Exception
		public RuleCall getExceptionsXmod_ExceptionParserRuleCall_7_1_0() { return cExceptionsXmod_ExceptionParserRuleCall_7_1_0; }
	}
	public class Xmod_OperationCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Xmod_OperationCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cXmod_OperationDefParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Xmod_OperationCall returns Xmod_Operation:
		//    'call' Xmod_OperationDef ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'call' Xmod_OperationDef ';'
		public Group getGroup() { return cGroup; }
		
		//'call'
		public Keyword getCallKeyword_0() { return cCallKeyword_0; }
		
		//Xmod_OperationDef
		public RuleCall getXmod_OperationDefParserRuleCall_1() { return cXmod_OperationDefParserRuleCall_1; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class Xmod_ExceptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Xmod_Exception");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOnErrorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cKindAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cKindXmod_ExceptionKind_UnfilteredParserRuleCall_1_0_0 = (RuleCall)cKindAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cKindAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cKindXmod_ExceptionKind_FilteredParserRuleCall_1_1_0_0 = (RuleCall)cKindAssignment_1_1_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cFilterAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cFilterEStringParserRuleCall_1_1_2_0 = (RuleCall)cFilterAssignment_1_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_1_3 = (Keyword)cGroup_1_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCallKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCalledOperationAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCalledOperationXmod_OperationDefParserRuleCall_2_1_0 = (RuleCall)cCalledOperationAssignment_2_1.eContents().get(0);
		private final Keyword cThenKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cReactionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cReactionXmod_ExceptionReactionEnumRuleCall_4_0 = (RuleCall)cReactionAssignment_4.eContents().get(0);
		
		//Xmod_Exception returns Xmod_Exception:
		//    'onError' (kind=Xmod_ExceptionKind_Unfiltered | kind=Xmod_ExceptionKind_Filtered '('filter=EString')')
		//    ('call' calledOperation=Xmod_OperationDef)? 'then' reaction=Xmod_ExceptionReaction;
		@Override public ParserRule getRule() { return rule; }
		
		//'onError' (kind=Xmod_ExceptionKind_Unfiltered | kind=Xmod_ExceptionKind_Filtered '('filter=EString')')
		//('call' calledOperation=Xmod_OperationDef)? 'then' reaction=Xmod_ExceptionReaction
		public Group getGroup() { return cGroup; }
		
		//'onError'
		public Keyword getOnErrorKeyword_0() { return cOnErrorKeyword_0; }
		
		//(kind=Xmod_ExceptionKind_Unfiltered | kind=Xmod_ExceptionKind_Filtered '('filter=EString')')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//kind=Xmod_ExceptionKind_Unfiltered
		public Assignment getKindAssignment_1_0() { return cKindAssignment_1_0; }
		
		//Xmod_ExceptionKind_Unfiltered
		public RuleCall getKindXmod_ExceptionKind_UnfilteredParserRuleCall_1_0_0() { return cKindXmod_ExceptionKind_UnfilteredParserRuleCall_1_0_0; }
		
		//kind=Xmod_ExceptionKind_Filtered '('filter=EString')'
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//kind=Xmod_ExceptionKind_Filtered
		public Assignment getKindAssignment_1_1_0() { return cKindAssignment_1_1_0; }
		
		//Xmod_ExceptionKind_Filtered
		public RuleCall getKindXmod_ExceptionKind_FilteredParserRuleCall_1_1_0_0() { return cKindXmod_ExceptionKind_FilteredParserRuleCall_1_1_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_1_1() { return cLeftParenthesisKeyword_1_1_1; }
		
		//filter=EString
		public Assignment getFilterAssignment_1_1_2() { return cFilterAssignment_1_1_2; }
		
		//EString
		public RuleCall getFilterEStringParserRuleCall_1_1_2_0() { return cFilterEStringParserRuleCall_1_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_1_3() { return cRightParenthesisKeyword_1_1_3; }
		
		//('call' calledOperation=Xmod_OperationDef)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'call'
		public Keyword getCallKeyword_2_0() { return cCallKeyword_2_0; }
		
		//calledOperation=Xmod_OperationDef
		public Assignment getCalledOperationAssignment_2_1() { return cCalledOperationAssignment_2_1; }
		
		//Xmod_OperationDef
		public RuleCall getCalledOperationXmod_OperationDefParserRuleCall_2_1_0() { return cCalledOperationXmod_OperationDefParserRuleCall_2_1_0; }
		
		//'then'
		public Keyword getThenKeyword_3() { return cThenKeyword_3; }
		
		//reaction=Xmod_ExceptionReaction
		public Assignment getReactionAssignment_4() { return cReactionAssignment_4; }
		
		//Xmod_ExceptionReaction
		public RuleCall getReactionXmod_ExceptionReactionEnumRuleCall_4_0() { return cReactionXmod_ExceptionReactionEnumRuleCall_4_0; }
	}
	public class Xmod_ExceptionKind_FilteredElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Xmod_ExceptionKind_Filtered");
		private final Keyword cMethodExceptionKeyword = (Keyword)rule.eContents().get(1);
		
		//Xmod_ExceptionKind_Filtered returns Xmod_ExceptionKind:
		//    'methodException';
		@Override public ParserRule getRule() { return rule; }
		
		//'methodException'
		public Keyword getMethodExceptionKeyword() { return cMethodExceptionKeyword; }
	}
	public class Xmod_ExceptionKind_UnfilteredElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Xmod_ExceptionKind_Unfiltered");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cOtherKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cUnknownNamespaceKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cObjectNotFoundKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cMethodNotFoundKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cParametersNotMatchingKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cReturnTypeNotMatchingKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//Xmod_ExceptionKind_Unfiltered returns Xmod_ExceptionKind:
		//    'other' | 'unknownNamespace' | 'objectNotFound' | 'methodNotFound' | 'parametersNotMatching' | 'returnTypeNotMatching';
		@Override public ParserRule getRule() { return rule; }
		
		//'other' | 'unknownNamespace' | 'objectNotFound' | 'methodNotFound' | 'parametersNotMatching' | 'returnTypeNotMatching'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'other'
		public Keyword getOtherKeyword_0() { return cOtherKeyword_0; }
		
		//'unknownNamespace'
		public Keyword getUnknownNamespaceKeyword_1() { return cUnknownNamespaceKeyword_1; }
		
		//'objectNotFound'
		public Keyword getObjectNotFoundKeyword_2() { return cObjectNotFoundKeyword_2; }
		
		//'methodNotFound'
		public Keyword getMethodNotFoundKeyword_3() { return cMethodNotFoundKeyword_3; }
		
		//'parametersNotMatching'
		public Keyword getParametersNotMatchingKeyword_4() { return cParametersNotMatchingKeyword_4; }
		
		//'returnTypeNotMatching'
		public Keyword getReturnTypeNotMatchingKeyword_5() { return cReturnTypeNotMatchingKeyword_5; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT '.' INT (('e'|'E') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT '.' INT (('e'|'E') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('e'|'E') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('e'|'E')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.EInt");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class ELongElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.ELong");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ELong returns ecore::ELong:
		//    INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	public class Xmod_ExceptionReactionElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Xmod_ExceptionReaction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cContinueEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cContinueContinueKeyword_0_0 = (Keyword)cContinueEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSkipEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSkipSkipKeyword_1_0 = (Keyword)cSkipEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cExitEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cExitExitKeyword_2_0 = (Keyword)cExitEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLocalstopEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLocalstopLocalstopKeyword_3_0 = (Keyword)cLocalstopEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Xmod_ExceptionReaction:
		//    continue | skip | exit | localstop;
		public EnumRule getRule() { return rule; }
		
		//continue | skip | exit | localstop
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//continue
		public EnumLiteralDeclaration getContinueEnumLiteralDeclaration_0() { return cContinueEnumLiteralDeclaration_0; }
		
		public Keyword getContinueContinueKeyword_0_0() { return cContinueContinueKeyword_0_0; }
		
		//skip
		public EnumLiteralDeclaration getSkipEnumLiteralDeclaration_1() { return cSkipEnumLiteralDeclaration_1; }
		
		public Keyword getSkipSkipKeyword_1_0() { return cSkipSkipKeyword_1_0; }
		
		//exit
		public EnumLiteralDeclaration getExitEnumLiteralDeclaration_2() { return cExitEnumLiteralDeclaration_2; }
		
		public Keyword getExitExitKeyword_2_0() { return cExitExitKeyword_2_0; }
		
		//localstop
		public EnumLiteralDeclaration getLocalstopEnumLiteralDeclaration_3() { return cLocalstopEnumLiteralDeclaration_3; }
		
		public Keyword getLocalstopLocalstopKeyword_3_0() { return cLocalstopLocalstopKeyword_3_0; }
	}
	public class Xmod_ExceptionKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Spice.Xmod_ExceptionKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOtherEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOtherOtherKeyword_0_0 = (Keyword)cOtherEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cUnknownNamespaceEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cUnknownNamespaceUnknownNamespaceKeyword_1_0 = (Keyword)cUnknownNamespaceEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cObjectNotFoundEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cObjectNotFoundObjectNotFoundKeyword_2_0 = (Keyword)cObjectNotFoundEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMethodNotFoundEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMethodNotFoundMethodNotFoundKeyword_3_0 = (Keyword)cMethodNotFoundEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cParametersNotMatchingEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cParametersNotMatchingParametersNotMatchingKeyword_4_0 = (Keyword)cParametersNotMatchingEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cReturnTypeNotMatchingEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cReturnTypeNotMatchingReturnTypeNotMatchingKeyword_5_0 = (Keyword)cReturnTypeNotMatchingEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cMethodExceptionEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cMethodExceptionMethodExceptionKeyword_6_0 = (Keyword)cMethodExceptionEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum Xmod_ExceptionKind:
		//    other = 'other' |
		//    unknownNamespace = 'unknownNamespace' |
		//    objectNotFound = 'objectNotFound' |
		//    methodNotFound = 'methodNotFound' |
		//    parametersNotMatching = 'parametersNotMatching' |
		//    returnTypeNotMatching = 'returnTypeNotMatching' |
		//    methodException = 'methodException';
		public EnumRule getRule() { return rule; }
		
		//other = 'other' |
		//unknownNamespace = 'unknownNamespace' |
		//objectNotFound = 'objectNotFound' |
		//methodNotFound = 'methodNotFound' |
		//parametersNotMatching = 'parametersNotMatching' |
		//returnTypeNotMatching = 'returnTypeNotMatching' |
		//methodException = 'methodException'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//other = 'other'
		public EnumLiteralDeclaration getOtherEnumLiteralDeclaration_0() { return cOtherEnumLiteralDeclaration_0; }
		
		//'other'
		public Keyword getOtherOtherKeyword_0_0() { return cOtherOtherKeyword_0_0; }
		
		//unknownNamespace = 'unknownNamespace'
		public EnumLiteralDeclaration getUnknownNamespaceEnumLiteralDeclaration_1() { return cUnknownNamespaceEnumLiteralDeclaration_1; }
		
		//'unknownNamespace'
		public Keyword getUnknownNamespaceUnknownNamespaceKeyword_1_0() { return cUnknownNamespaceUnknownNamespaceKeyword_1_0; }
		
		//objectNotFound = 'objectNotFound'
		public EnumLiteralDeclaration getObjectNotFoundEnumLiteralDeclaration_2() { return cObjectNotFoundEnumLiteralDeclaration_2; }
		
		//'objectNotFound'
		public Keyword getObjectNotFoundObjectNotFoundKeyword_2_0() { return cObjectNotFoundObjectNotFoundKeyword_2_0; }
		
		//methodNotFound = 'methodNotFound'
		public EnumLiteralDeclaration getMethodNotFoundEnumLiteralDeclaration_3() { return cMethodNotFoundEnumLiteralDeclaration_3; }
		
		//'methodNotFound'
		public Keyword getMethodNotFoundMethodNotFoundKeyword_3_0() { return cMethodNotFoundMethodNotFoundKeyword_3_0; }
		
		//parametersNotMatching = 'parametersNotMatching'
		public EnumLiteralDeclaration getParametersNotMatchingEnumLiteralDeclaration_4() { return cParametersNotMatchingEnumLiteralDeclaration_4; }
		
		//'parametersNotMatching'
		public Keyword getParametersNotMatchingParametersNotMatchingKeyword_4_0() { return cParametersNotMatchingParametersNotMatchingKeyword_4_0; }
		
		//returnTypeNotMatching = 'returnTypeNotMatching'
		public EnumLiteralDeclaration getReturnTypeNotMatchingEnumLiteralDeclaration_5() { return cReturnTypeNotMatchingEnumLiteralDeclaration_5; }
		
		//'returnTypeNotMatching'
		public Keyword getReturnTypeNotMatchingReturnTypeNotMatchingKeyword_5_0() { return cReturnTypeNotMatchingReturnTypeNotMatchingKeyword_5_0; }
		
		//methodException = 'methodException'
		public EnumLiteralDeclaration getMethodExceptionEnumLiteralDeclaration_6() { return cMethodExceptionEnumLiteralDeclaration_6; }
		
		//'methodException'
		public Keyword getMethodExceptionMethodExceptionKeyword_6_0() { return cMethodExceptionMethodExceptionKeyword_6_0; }
	}
	
	private final SimulationElements pSimulation;
	private final ComponentElements pComponent;
	private final ViewElements pView;
	private final AttributeElements pAttribute;
	private final IntBasicElements pIntBasic;
	private final IntArrayElements pIntArray;
	private final DoubleBasicElements pDoubleBasic;
	private final DoubleArrayElements pDoubleArray;
	private final StringBasicElements pStringBasic;
	private final StringArrayElements pStringArray;
	private final BooleanBasicElements pBooleanBasic;
	private final BooleanArrayElements pBooleanArray;
	private final Xmod_ActionElements pXmod_Action;
	private final Xmod_OperationDefElements pXmod_OperationDef;
	private final Xmod_OperationCallElements pXmod_OperationCall;
	private final Xmod_ExceptionElements pXmod_Exception;
	private final Xmod_ExceptionReactionElements eXmod_ExceptionReaction;
	private final Xmod_ExceptionKindElements eXmod_ExceptionKind;
	private final Xmod_ExceptionKind_FilteredElements pXmod_ExceptionKind_Filtered;
	private final Xmod_ExceptionKind_UnfilteredElements pXmod_ExceptionKind_Unfiltered;
	private final EDoubleElements pEDouble;
	private final EIntElements pEInt;
	private final ELongElements pELong;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SpiceGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSimulation = new SimulationElements();
		this.pComponent = new ComponentElements();
		this.pView = new ViewElements();
		this.pAttribute = new AttributeElements();
		this.pIntBasic = new IntBasicElements();
		this.pIntArray = new IntArrayElements();
		this.pDoubleBasic = new DoubleBasicElements();
		this.pDoubleArray = new DoubleArrayElements();
		this.pStringBasic = new StringBasicElements();
		this.pStringArray = new StringArrayElements();
		this.pBooleanBasic = new BooleanBasicElements();
		this.pBooleanArray = new BooleanArrayElements();
		this.pXmod_Action = new Xmod_ActionElements();
		this.pXmod_OperationDef = new Xmod_OperationDefElements();
		this.pXmod_OperationCall = new Xmod_OperationCallElements();
		this.pXmod_Exception = new Xmod_ExceptionElements();
		this.eXmod_ExceptionReaction = new Xmod_ExceptionReactionElements();
		this.eXmod_ExceptionKind = new Xmod_ExceptionKindElements();
		this.pXmod_ExceptionKind_Filtered = new Xmod_ExceptionKind_FilteredElements();
		this.pXmod_ExceptionKind_Unfiltered = new Xmod_ExceptionKind_UnfilteredElements();
		this.pEDouble = new EDoubleElements();
		this.pEInt = new EIntElements();
		this.pELong = new ELongElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.Spice".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Simulation returns Simulation:
	//    'Simulation' 'xmod_id:' xmod_id=EString '('startTime=ELong',' endTime=ELong',' durationStep=ELong')' '{'
	//        ( components+=Component (components+=Component)* )?
	//        ( views+=View (views+=View)* )?
	//    '}';
	public SimulationElements getSimulationAccess() {
		return pSimulation;
	}
	
	public ParserRule getSimulationRule() {
		return getSimulationAccess().getRule();
	}
	
	//Component returns Component:
	//    'Component' 'xmod_id:' xmod_id=EString '('priority=ELong',' period=ELong')' (isDataFlow?='DF')? '{'
	//        ( attributes+=Attribute ( attributes+=Attribute )* )?
	//        ( actions+=Xmod_Action ( actions+=Xmod_Action )* )?
	//    '}';
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//View returns View:
	//    'View' 'xmod_id:' xmod_id=EString '{'
	//        ( 'host' host=EString )?
	//        ( 'port' port=EInt )?
	//        ( 'period' period=ELong )?
	//        ( 'observe' observedTags+=EString ( ',' observedTags+=EString )* ';' )?
	//    '}';
	public ViewElements getViewAccess() {
		return pView;
	}
	
	public ParserRule getViewRule() {
		return getViewAccess().getRule();
	}
	
	//Attribute returns Attribute:
	//    IntBasic | IntArray |
	//    DoubleBasic | DoubleArray |
	//    StringBasic | StringArray |
	//    BooleanBasic | BooleanArray;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//IntBasic returns BasicAttribute:
	//    (isObservable?='observable')? type=EString name=EString '=' value=EInt ';';
	public IntBasicElements getIntBasicAccess() {
		return pIntBasic;
	}
	
	public ParserRule getIntBasicRule() {
		return getIntBasicAccess().getRule();
	}
	
	//IntArray returns ArrayAttribute:
	//    (isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EInt ',' value+=EInt ( ',' value+=EInt )*')') ';';
	public IntArrayElements getIntArrayAccess() {
		return pIntArray;
	}
	
	public ParserRule getIntArrayRule() {
		return getIntArrayAccess().getRule();
	}
	
	//DoubleBasic returns BasicAttribute:
	//    (isObservable?='observable')? type=EString name=EString '=' value=EDouble ';';
	public DoubleBasicElements getDoubleBasicAccess() {
		return pDoubleBasic;
	}
	
	public ParserRule getDoubleBasicRule() {
		return getDoubleBasicAccess().getRule();
	}
	
	//DoubleArray returns ArrayAttribute:
	//    (isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EDouble ',' value+=EDouble ( ',' value+=EDouble )*')') ';';
	public DoubleArrayElements getDoubleArrayAccess() {
		return pDoubleArray;
	}
	
	public ParserRule getDoubleArrayRule() {
		return getDoubleArrayAccess().getRule();
	}
	
	//StringBasic returns BasicAttribute:
	//    (isObservable?='observable')? type=EString name=EString '=' value=EString ';';
	public StringBasicElements getStringBasicAccess() {
		return pStringBasic;
	}
	
	public ParserRule getStringBasicRule() {
		return getStringBasicAccess().getRule();
	}
	
	//StringArray returns ArrayAttribute:
	//    (isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EString ',' value+=EString ( ',' value+=EString )*')') ';';
	public StringArrayElements getStringArrayAccess() {
		return pStringArray;
	}
	
	public ParserRule getStringArrayRule() {
		return getStringArrayAccess().getRule();
	}
	
	//BooleanBasic returns BasicAttribute:
	//    (isObservable?='observable')? type=EString name=EString '=' value=EBoolean ';';
	public BooleanBasicElements getBooleanBasicAccess() {
		return pBooleanBasic;
	}
	
	public ParserRule getBooleanBasicRule() {
		return getBooleanBasicAccess().getRule();
	}
	
	//BooleanArray returns ArrayAttribute:
	//    (isObservable?='observable')? type=EString ('['multiplicity=ELong']')? name=EString '=' ('('value+=EBoolean ',' value+=EBoolean ( ',' value+=EBoolean )*')') ';';
	public BooleanArrayElements getBooleanArrayAccess() {
		return pBooleanArray;
	}
	
	public ParserRule getBooleanArrayRule() {
		return getBooleanArrayAccess().getRule();
	}
	
	//Xmod_Action returns Xmod_Action:
	//    'Action' name=EString '{' operations+=Xmod_OperationCall (operations+=Xmod_OperationCall)* '}';
	public Xmod_ActionElements getXmod_ActionAccess() {
		return pXmod_Action;
	}
	
	public ParserRule getXmod_ActionRule() {
		return getXmod_ActionAccess().getRule();
	}
	
	//Xmod_OperationDef returns Xmod_Operation:
	//    name=EString'('( parametersTag+=EString ( "," parametersTag+=EString )* )?')'
	//        'on' objectTag=EString ('returns' returnTag=EString)?
	//        (exceptions+=Xmod_Exception (exceptions+=Xmod_Exception)* )?;
	public Xmod_OperationDefElements getXmod_OperationDefAccess() {
		return pXmod_OperationDef;
	}
	
	public ParserRule getXmod_OperationDefRule() {
		return getXmod_OperationDefAccess().getRule();
	}
	
	//Xmod_OperationCall returns Xmod_Operation:
	//    'call' Xmod_OperationDef ';';
	public Xmod_OperationCallElements getXmod_OperationCallAccess() {
		return pXmod_OperationCall;
	}
	
	public ParserRule getXmod_OperationCallRule() {
		return getXmod_OperationCallAccess().getRule();
	}
	
	//Xmod_Exception returns Xmod_Exception:
	//    'onError' (kind=Xmod_ExceptionKind_Unfiltered | kind=Xmod_ExceptionKind_Filtered '('filter=EString')')
	//    ('call' calledOperation=Xmod_OperationDef)? 'then' reaction=Xmod_ExceptionReaction;
	public Xmod_ExceptionElements getXmod_ExceptionAccess() {
		return pXmod_Exception;
	}
	
	public ParserRule getXmod_ExceptionRule() {
		return getXmod_ExceptionAccess().getRule();
	}
	
	//enum Xmod_ExceptionReaction:
	//    continue | skip | exit | localstop;
	public Xmod_ExceptionReactionElements getXmod_ExceptionReactionAccess() {
		return eXmod_ExceptionReaction;
	}
	
	public EnumRule getXmod_ExceptionReactionRule() {
		return getXmod_ExceptionReactionAccess().getRule();
	}
	
	//enum Xmod_ExceptionKind:
	//    other = 'other' |
	//    unknownNamespace = 'unknownNamespace' |
	//    objectNotFound = 'objectNotFound' |
	//    methodNotFound = 'methodNotFound' |
	//    parametersNotMatching = 'parametersNotMatching' |
	//    returnTypeNotMatching = 'returnTypeNotMatching' |
	//    methodException = 'methodException';
	public Xmod_ExceptionKindElements getXmod_ExceptionKindAccess() {
		return eXmod_ExceptionKind;
	}
	
	public EnumRule getXmod_ExceptionKindRule() {
		return getXmod_ExceptionKindAccess().getRule();
	}
	
	//Xmod_ExceptionKind_Filtered returns Xmod_ExceptionKind:
	//    'methodException';
	public Xmod_ExceptionKind_FilteredElements getXmod_ExceptionKind_FilteredAccess() {
		return pXmod_ExceptionKind_Filtered;
	}
	
	public ParserRule getXmod_ExceptionKind_FilteredRule() {
		return getXmod_ExceptionKind_FilteredAccess().getRule();
	}
	
	//Xmod_ExceptionKind_Unfiltered returns Xmod_ExceptionKind:
	//    'other' | 'unknownNamespace' | 'objectNotFound' | 'methodNotFound' | 'parametersNotMatching' | 'returnTypeNotMatching';
	public Xmod_ExceptionKind_UnfilteredElements getXmod_ExceptionKind_UnfilteredAccess() {
		return pXmod_ExceptionKind_Unfiltered;
	}
	
	public ParserRule getXmod_ExceptionKind_UnfilteredRule() {
		return getXmod_ExceptionKind_UnfilteredAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT '.' INT (('e'|'E') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//ELong returns ecore::ELong:
	//    INT;
	public ELongElements getELongAccess() {
		return pELong;
	}
	
	public ParserRule getELongRule() {
		return getELongAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
