/*
 * generated by Xtext 2.40.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.SpiceRuntimeModule;
import org.xtext.SpiceStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SpiceIdeSetup extends SpiceStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SpiceRuntimeModule(), new SpiceIdeModule()));
	}
	
}
