/*
 * generated by Xtext 2.40.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtextSpice.ui.internal.XtextSpiceActivator;

public class SpiceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextSpiceActivator.getInstance().getInjector("org.xtext.Spice");
	}

}
