/*
 * generated by Xtext 2.40.0
 */
package org.xtext.serializer;

import Spice.ArrayAttribute;
import Spice.BasicAttribute;
import Spice.Component;
import Spice.Simulation;
import Spice.SpicePackage;
import Spice.View;
import Spice.Xmod_Action;
import Spice.Xmod_Exception;
import Spice.Xmod_Operation;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.services.SpiceGrammarAccess;

@SuppressWarnings("all")
public class SpiceSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SpiceGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SpicePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SpicePackage.ARRAY_ATTRIBUTE:
				if (rule == grammarAccess.getBooleanArrayRule()) {
					sequence_BooleanArray(context, (ArrayAttribute) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getAttributeRule()) {
					sequence_BooleanArray_DoubleArray_IntArray_StringArray(context, (ArrayAttribute) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getDoubleArrayRule()) {
					sequence_DoubleArray(context, (ArrayAttribute) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getIntArrayRule()) {
					sequence_IntArray(context, (ArrayAttribute) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getStringArrayRule()) {
					sequence_StringArray(context, (ArrayAttribute) semanticObject); 
					return; 
				}
				else break;
			case SpicePackage.BASIC_ATTRIBUTE:
				if (rule == grammarAccess.getBooleanBasicRule()) {
					sequence_BooleanBasic(context, (BasicAttribute) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getAttributeRule()) {
					sequence_BooleanBasic_DoubleBasic_IntBasic_StringBasic(context, (BasicAttribute) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getDoubleBasicRule()) {
					sequence_DoubleBasic(context, (BasicAttribute) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getIntBasicRule()) {
					sequence_IntBasic(context, (BasicAttribute) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getStringBasicRule()) {
					sequence_StringBasic(context, (BasicAttribute) semanticObject); 
					return; 
				}
				else break;
			case SpicePackage.COMPONENT:
				sequence_Component(context, (Component) semanticObject); 
				return; 
			case SpicePackage.SIMULATION:
				sequence_Simulation(context, (Simulation) semanticObject); 
				return; 
			case SpicePackage.VIEW:
				sequence_View(context, (View) semanticObject); 
				return; 
			case SpicePackage.XMOD_ACTION:
				sequence_Xmod_Action(context, (Xmod_Action) semanticObject); 
				return; 
			case SpicePackage.XMOD_EXCEPTION:
				sequence_Xmod_Exception(context, (Xmod_Exception) semanticObject); 
				return; 
			case SpicePackage.XMOD_OPERATION:
				sequence_Xmod_OperationDef(context, (Xmod_Operation) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     BooleanArray returns ArrayAttribute
	 *
	 * Constraint:
	 *     (
	 *         isObservable?='observable'? 
	 *         type=EString 
	 *         multiplicity=ELong? 
	 *         name=EString 
	 *         value+=EBoolean 
	 *         value+=EBoolean 
	 *         value+=EBoolean*
	 *     )
	 * </pre>
	 */
	protected void sequence_BooleanArray(ISerializationContext context, ArrayAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Attribute returns ArrayAttribute
	 *
	 * Constraint:
	 *     (
	 *         (
	 *             isObservable?='observable'? 
	 *             type=EString 
	 *             multiplicity=ELong? 
	 *             name=EString 
	 *             value+=EInt 
	 *             value+=EInt 
	 *             value+=EInt*
	 *         ) | 
	 *         (
	 *             isObservable?='observable'? 
	 *             type=EString 
	 *             multiplicity=ELong? 
	 *             name=EString 
	 *             value+=EDouble 
	 *             value+=EDouble 
	 *             value+=EDouble*
	 *         ) | 
	 *         (
	 *             isObservable?='observable'? 
	 *             type=EString 
	 *             multiplicity=ELong? 
	 *             name=EString 
	 *             value+=EString 
	 *             value+=EString 
	 *             value+=EString*
	 *         ) | 
	 *         (
	 *             isObservable?='observable'? 
	 *             type=EString 
	 *             multiplicity=ELong? 
	 *             name=EString 
	 *             value+=EBoolean 
	 *             value+=EBoolean 
	 *             value+=EBoolean*
	 *         )
	 *     )
	 * </pre>
	 */
	protected void sequence_BooleanArray_DoubleArray_IntArray_StringArray(ISerializationContext context, ArrayAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     BooleanBasic returns BasicAttribute
	 *
	 * Constraint:
	 *     (isObservable?='observable'? type=EString name=EString value=EBoolean)
	 * </pre>
	 */
	protected void sequence_BooleanBasic(ISerializationContext context, BasicAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Attribute returns BasicAttribute
	 *
	 * Constraint:
	 *     (
	 *         (isObservable?='observable'? type=EString name=EString value=EInt) | 
	 *         (isObservable?='observable'? type=EString name=EString value=EDouble) | 
	 *         (isObservable?='observable'? type=EString name=EString value=EString) | 
	 *         (isObservable?='observable'? type=EString name=EString value=EBoolean)
	 *     )
	 * </pre>
	 */
	protected void sequence_BooleanBasic_DoubleBasic_IntBasic_StringBasic(ISerializationContext context, BasicAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Component returns Component
	 *
	 * Constraint:
	 *     (
	 *         xmod_id=EString 
	 *         priority=ELong 
	 *         period=ELong 
	 *         isDataFlow?='DF'? 
	 *         (attributes+=Attribute attributes+=Attribute*)? 
	 *         (actions+=Xmod_Action actions+=Xmod_Action*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Component(ISerializationContext context, Component semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DoubleArray returns ArrayAttribute
	 *
	 * Constraint:
	 *     (
	 *         isObservable?='observable'? 
	 *         type=EString 
	 *         multiplicity=ELong? 
	 *         name=EString 
	 *         value+=EDouble 
	 *         value+=EDouble 
	 *         value+=EDouble*
	 *     )
	 * </pre>
	 */
	protected void sequence_DoubleArray(ISerializationContext context, ArrayAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DoubleBasic returns BasicAttribute
	 *
	 * Constraint:
	 *     (isObservable?='observable'? type=EString name=EString value=EDouble)
	 * </pre>
	 */
	protected void sequence_DoubleBasic(ISerializationContext context, BasicAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     IntArray returns ArrayAttribute
	 *
	 * Constraint:
	 *     (
	 *         isObservable?='observable'? 
	 *         type=EString 
	 *         multiplicity=ELong? 
	 *         name=EString 
	 *         value+=EInt 
	 *         value+=EInt 
	 *         value+=EInt*
	 *     )
	 * </pre>
	 */
	protected void sequence_IntArray(ISerializationContext context, ArrayAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     IntBasic returns BasicAttribute
	 *
	 * Constraint:
	 *     (isObservable?='observable'? type=EString name=EString value=EInt)
	 * </pre>
	 */
	protected void sequence_IntBasic(ISerializationContext context, BasicAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Simulation returns Simulation
	 *
	 * Constraint:
	 *     (
	 *         xmod_id=EString 
	 *         startTime=ELong 
	 *         endTime=ELong 
	 *         durationStep=ELong 
	 *         (components+=Component components+=Component*)? 
	 *         (views+=View views+=View*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Simulation(ISerializationContext context, Simulation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StringArray returns ArrayAttribute
	 *
	 * Constraint:
	 *     (
	 *         isObservable?='observable'? 
	 *         type=EString 
	 *         multiplicity=ELong? 
	 *         name=EString 
	 *         value+=EString 
	 *         value+=EString 
	 *         value+=EString*
	 *     )
	 * </pre>
	 */
	protected void sequence_StringArray(ISerializationContext context, ArrayAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StringBasic returns BasicAttribute
	 *
	 * Constraint:
	 *     (isObservable?='observable'? type=EString name=EString value=EString)
	 * </pre>
	 */
	protected void sequence_StringBasic(ISerializationContext context, BasicAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     View returns View
	 *
	 * Constraint:
	 *     (xmod_id=EString host=EString? port=EInt? period=ELong? (observedTags+=EString observedTags+=EString*)?)
	 * </pre>
	 */
	protected void sequence_View(ISerializationContext context, View semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Xmod_Action returns Xmod_Action
	 *
	 * Constraint:
	 *     (name=EString operations+=Xmod_OperationCall operations+=Xmod_OperationCall*)
	 * </pre>
	 */
	protected void sequence_Xmod_Action(ISerializationContext context, Xmod_Action semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Xmod_Exception returns Xmod_Exception
	 *
	 * Constraint:
	 *     (
	 *         (kind=Xmod_ExceptionKind_Unfiltered | (kind=Xmod_ExceptionKind_Filtered filter=EString)) 
	 *         calledOperation=Xmod_OperationDef? 
	 *         reaction=Xmod_ExceptionReaction
	 *     )
	 * </pre>
	 */
	protected void sequence_Xmod_Exception(ISerializationContext context, Xmod_Exception semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Xmod_OperationDef returns Xmod_Operation
	 *     Xmod_OperationCall returns Xmod_Operation
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (parametersTag+=EString parametersTag+=EString*)? 
	 *         objectTag=EString 
	 *         returnTag=EString? 
	 *         (exceptions+=Xmod_Exception exceptions+=Xmod_Exception*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Xmod_OperationDef(ISerializationContext context, Xmod_Operation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
