/*
 * generated by Xtext 2.40.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalSpiceParser;
import org.xtext.services.SpiceGrammarAccess;

public class SpiceParser extends AbstractAntlrParser {

	@Inject
	private SpiceGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSpiceParser createParser(XtextTokenStream stream) {
		return new InternalSpiceParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Simulation";
	}

	public SpiceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SpiceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
