/*
 * generated by Xtext 2.40.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import xtextSpice.ui.internal.XtextSpiceActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpiceExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XtextSpiceActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XtextSpiceActivator activator = XtextSpiceActivator.getInstance();
		return activator != null ? activator.getInjector(XtextSpiceActivator.ORG_XTEXT_SPICE) : null;
	}

}
