/*
 * generated by Xtext 2.40.0
 */
grammar InternalSpice;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.services.SpiceGrammarAccess;

}

@parser::members {

 	private SpiceGrammarAccess grammarAccess;

    public InternalSpiceParser(TokenStream input, SpiceGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Simulation";
   	}

   	@Override
   	protected SpiceGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleSimulation
entryRuleSimulation returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSimulationRule()); }
	iv_ruleSimulation=ruleSimulation
	{ $current=$iv_ruleSimulation.current; }
	EOF;

// Rule Simulation
ruleSimulation returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Simulation'
		{
			newLeafNode(otherlv_0, grammarAccess.getSimulationAccess().getSimulationKeyword_0());
		}
		otherlv_1='xmod_id:'
		{
			newLeafNode(otherlv_1, grammarAccess.getSimulationAccess().getXmod_idKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimulationAccess().getXmod_idEStringParserRuleCall_2_0());
				}
				lv_xmod_id_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimulationRule());
					}
					set(
						$current,
						"xmod_id",
						lv_xmod_id_2_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='('
		{
			newLeafNode(otherlv_3, grammarAccess.getSimulationAccess().getLeftParenthesisKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimulationAccess().getStartTimeELongParserRuleCall_4_0());
				}
				lv_startTime_4_0=ruleELong
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimulationRule());
					}
					set(
						$current,
						"startTime",
						lv_startTime_4_0,
						"org.xtext.Spice.ELong");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5=','
		{
			newLeafNode(otherlv_5, grammarAccess.getSimulationAccess().getCommaKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimulationAccess().getEndTimeELongParserRuleCall_6_0());
				}
				lv_endTime_6_0=ruleELong
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimulationRule());
					}
					set(
						$current,
						"endTime",
						lv_endTime_6_0,
						"org.xtext.Spice.ELong");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7=','
		{
			newLeafNode(otherlv_7, grammarAccess.getSimulationAccess().getCommaKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSimulationAccess().getDurationStepELongParserRuleCall_8_0());
				}
				lv_durationStep_8_0=ruleELong
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSimulationRule());
					}
					set(
						$current,
						"durationStep",
						lv_durationStep_8_0,
						"org.xtext.Spice.ELong");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_9=')'
		{
			newLeafNode(otherlv_9, grammarAccess.getSimulationAccess().getRightParenthesisKeyword_9());
		}
		otherlv_10='{'
		{
			newLeafNode(otherlv_10, grammarAccess.getSimulationAccess().getLeftCurlyBracketKeyword_10());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getSimulationAccess().getComponentsComponentParserRuleCall_11_0_0());
					}
					lv_components_11_0=ruleComponent
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSimulationRule());
						}
						add(
							$current,
							"components",
							lv_components_11_0,
							"org.xtext.Spice.Component");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getSimulationAccess().getComponentsComponentParserRuleCall_11_1_0());
					}
					lv_components_12_0=ruleComponent
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSimulationRule());
						}
						add(
							$current,
							"components",
							lv_components_12_0,
							"org.xtext.Spice.Component");
						afterParserOrEnumRuleCall();
					}
				)
			)*
		)?
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getSimulationAccess().getViewsViewParserRuleCall_12_0_0());
					}
					lv_views_13_0=ruleView
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSimulationRule());
						}
						add(
							$current,
							"views",
							lv_views_13_0,
							"org.xtext.Spice.View");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getSimulationAccess().getViewsViewParserRuleCall_12_1_0());
					}
					lv_views_14_0=ruleView
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSimulationRule());
						}
						add(
							$current,
							"views",
							lv_views_14_0,
							"org.xtext.Spice.View");
						afterParserOrEnumRuleCall();
					}
				)
			)*
		)?
		otherlv_15='}'
		{
			newLeafNode(otherlv_15, grammarAccess.getSimulationAccess().getRightCurlyBracketKeyword_13());
		}
	)
;

// Entry rule entryRuleComponent
entryRuleComponent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getComponentRule()); }
	iv_ruleComponent=ruleComponent
	{ $current=$iv_ruleComponent.current; }
	EOF;

// Rule Component
ruleComponent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Component'
		{
			newLeafNode(otherlv_0, grammarAccess.getComponentAccess().getComponentKeyword_0());
		}
		otherlv_1='xmod_id:'
		{
			newLeafNode(otherlv_1, grammarAccess.getComponentAccess().getXmod_idKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getComponentAccess().getXmod_idEStringParserRuleCall_2_0());
				}
				lv_xmod_id_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getComponentRule());
					}
					set(
						$current,
						"xmod_id",
						lv_xmod_id_2_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='('
		{
			newLeafNode(otherlv_3, grammarAccess.getComponentAccess().getLeftParenthesisKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getComponentAccess().getPriorityELongParserRuleCall_4_0());
				}
				lv_priority_4_0=ruleELong
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getComponentRule());
					}
					set(
						$current,
						"priority",
						lv_priority_4_0,
						"org.xtext.Spice.ELong");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5=','
		{
			newLeafNode(otherlv_5, grammarAccess.getComponentAccess().getCommaKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getComponentAccess().getPeriodELongParserRuleCall_6_0());
				}
				lv_period_6_0=ruleELong
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getComponentRule());
					}
					set(
						$current,
						"period",
						lv_period_6_0,
						"org.xtext.Spice.ELong");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7=')'
		{
			newLeafNode(otherlv_7, grammarAccess.getComponentAccess().getRightParenthesisKeyword_7());
		}
		(
			(
				lv_isDataFlow_8_0='DF'
				{
					newLeafNode(lv_isDataFlow_8_0, grammarAccess.getComponentAccess().getIsDataFlowDFKeyword_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getComponentRule());
					}
					setWithLastConsumed($current, "isDataFlow", lv_isDataFlow_8_0 != null, "DF");
				}
			)
		)?
		otherlv_9='{'
		{
			newLeafNode(otherlv_9, grammarAccess.getComponentAccess().getLeftCurlyBracketKeyword_9());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getComponentAccess().getAttributesAttributeParserRuleCall_10_0_0());
					}
					lv_attributes_10_0=ruleAttribute
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getComponentRule());
						}
						add(
							$current,
							"attributes",
							lv_attributes_10_0,
							"org.xtext.Spice.Attribute");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getComponentAccess().getAttributesAttributeParserRuleCall_10_1_0());
					}
					lv_attributes_11_0=ruleAttribute
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getComponentRule());
						}
						add(
							$current,
							"attributes",
							lv_attributes_11_0,
							"org.xtext.Spice.Attribute");
						afterParserOrEnumRuleCall();
					}
				)
			)*
		)?
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getComponentAccess().getActionsXmod_ActionParserRuleCall_11_0_0());
					}
					lv_actions_12_0=ruleXmod_Action
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getComponentRule());
						}
						add(
							$current,
							"actions",
							lv_actions_12_0,
							"org.xtext.Spice.Xmod_Action");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getComponentAccess().getActionsXmod_ActionParserRuleCall_11_1_0());
					}
					lv_actions_13_0=ruleXmod_Action
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getComponentRule());
						}
						add(
							$current,
							"actions",
							lv_actions_13_0,
							"org.xtext.Spice.Xmod_Action");
						afterParserOrEnumRuleCall();
					}
				)
			)*
		)?
		otherlv_14='}'
		{
			newLeafNode(otherlv_14, grammarAccess.getComponentAccess().getRightCurlyBracketKeyword_12());
		}
	)
;

// Entry rule entryRuleView
entryRuleView returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getViewRule()); }
	iv_ruleView=ruleView
	{ $current=$iv_ruleView.current; }
	EOF;

// Rule View
ruleView returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='View'
		{
			newLeafNode(otherlv_0, grammarAccess.getViewAccess().getViewKeyword_0());
		}
		otherlv_1='xmod_id:'
		{
			newLeafNode(otherlv_1, grammarAccess.getViewAccess().getXmod_idKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getViewAccess().getXmod_idEStringParserRuleCall_2_0());
				}
				lv_xmod_id_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getViewRule());
					}
					set(
						$current,
						"xmod_id",
						lv_xmod_id_2_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getViewAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			otherlv_4='host'
			{
				newLeafNode(otherlv_4, grammarAccess.getViewAccess().getHostKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getViewAccess().getHostEStringParserRuleCall_4_1_0());
					}
					lv_host_5_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getViewRule());
						}
						set(
							$current,
							"host",
							lv_host_5_0,
							"org.xtext.Spice.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_6='port'
			{
				newLeafNode(otherlv_6, grammarAccess.getViewAccess().getPortKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getViewAccess().getPortEIntParserRuleCall_5_1_0());
					}
					lv_port_7_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getViewRule());
						}
						set(
							$current,
							"port",
							lv_port_7_0,
							"org.xtext.Spice.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_8='period'
			{
				newLeafNode(otherlv_8, grammarAccess.getViewAccess().getPeriodKeyword_6_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getViewAccess().getPeriodELongParserRuleCall_6_1_0());
					}
					lv_period_9_0=ruleELong
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getViewRule());
						}
						set(
							$current,
							"period",
							lv_period_9_0,
							"org.xtext.Spice.ELong");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_10='observe'
			{
				newLeafNode(otherlv_10, grammarAccess.getViewAccess().getObserveKeyword_7_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getViewAccess().getObservedTagsEStringParserRuleCall_7_1_0());
					}
					lv_observedTags_11_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getViewRule());
						}
						add(
							$current,
							"observedTags",
							lv_observedTags_11_0,
							"org.xtext.Spice.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_12=','
				{
					newLeafNode(otherlv_12, grammarAccess.getViewAccess().getCommaKeyword_7_2_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getViewAccess().getObservedTagsEStringParserRuleCall_7_2_1_0());
						}
						lv_observedTags_13_0=ruleEString
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getViewRule());
							}
							add(
								$current,
								"observedTags",
								lv_observedTags_13_0,
								"org.xtext.Spice.EString");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_14=';'
			{
				newLeafNode(otherlv_14, grammarAccess.getViewAccess().getSemicolonKeyword_7_3());
			}
		)?
		otherlv_15='}'
		{
			newLeafNode(otherlv_15, grammarAccess.getViewAccess().getRightCurlyBracketKeyword_8());
		}
	)
;

// Entry rule entryRuleAttribute
entryRuleAttribute returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAttributeRule()); }
	iv_ruleAttribute=ruleAttribute
	{ $current=$iv_ruleAttribute.current; }
	EOF;

// Rule Attribute
ruleAttribute returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getAttributeAccess().getIntBasicParserRuleCall_0());
		}
		this_IntBasic_0=ruleIntBasic
		{
			$current = $this_IntBasic_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAttributeAccess().getIntArrayParserRuleCall_1());
		}
		this_IntArray_1=ruleIntArray
		{
			$current = $this_IntArray_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAttributeAccess().getDoubleBasicParserRuleCall_2());
		}
		this_DoubleBasic_2=ruleDoubleBasic
		{
			$current = $this_DoubleBasic_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAttributeAccess().getDoubleArrayParserRuleCall_3());
		}
		this_DoubleArray_3=ruleDoubleArray
		{
			$current = $this_DoubleArray_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAttributeAccess().getStringBasicParserRuleCall_4());
		}
		this_StringBasic_4=ruleStringBasic
		{
			$current = $this_StringBasic_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAttributeAccess().getStringArrayParserRuleCall_5());
		}
		this_StringArray_5=ruleStringArray
		{
			$current = $this_StringArray_5.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAttributeAccess().getBooleanBasicParserRuleCall_6());
		}
		this_BooleanBasic_6=ruleBooleanBasic
		{
			$current = $this_BooleanBasic_6.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAttributeAccess().getBooleanArrayParserRuleCall_7());
		}
		this_BooleanArray_7=ruleBooleanArray
		{
			$current = $this_BooleanArray_7.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleIntBasic
entryRuleIntBasic returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getIntBasicRule()); }
	iv_ruleIntBasic=ruleIntBasic
	{ $current=$iv_ruleIntBasic.current; }
	EOF;

// Rule IntBasic
ruleIntBasic returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_isObservable_0_0='observable'
				{
					newLeafNode(lv_isObservable_0_0, grammarAccess.getIntBasicAccess().getIsObservableObservableKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getIntBasicRule());
					}
					setWithLastConsumed($current, "isObservable", lv_isObservable_0_0 != null, "observable");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getIntBasicAccess().getTypeEStringParserRuleCall_1_0());
				}
				lv_type_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getIntBasicRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getIntBasicAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getIntBasicRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='='
		{
			newLeafNode(otherlv_3, grammarAccess.getIntBasicAccess().getEqualsSignKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getIntBasicAccess().getValueEIntParserRuleCall_4_0());
				}
				lv_value_4_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getIntBasicRule());
					}
					set(
						$current,
						"value",
						lv_value_4_0,
						"org.xtext.Spice.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5=';'
		{
			newLeafNode(otherlv_5, grammarAccess.getIntBasicAccess().getSemicolonKeyword_5());
		}
	)
;

// Entry rule entryRuleIntArray
entryRuleIntArray returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getIntArrayRule()); }
	iv_ruleIntArray=ruleIntArray
	{ $current=$iv_ruleIntArray.current; }
	EOF;

// Rule IntArray
ruleIntArray returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_isObservable_0_0='observable'
				{
					newLeafNode(lv_isObservable_0_0, grammarAccess.getIntArrayAccess().getIsObservableObservableKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getIntArrayRule());
					}
					setWithLastConsumed($current, "isObservable", lv_isObservable_0_0 != null, "observable");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getIntArrayAccess().getTypeEStringParserRuleCall_1_0());
				}
				lv_type_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getIntArrayRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_2='['
			{
				newLeafNode(otherlv_2, grammarAccess.getIntArrayAccess().getLeftSquareBracketKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getIntArrayAccess().getMultiplicityELongParserRuleCall_2_1_0());
					}
					lv_multiplicity_3_0=ruleELong
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getIntArrayRule());
						}
						set(
							$current,
							"multiplicity",
							lv_multiplicity_3_0,
							"org.xtext.Spice.ELong");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_4=']'
			{
				newLeafNode(otherlv_4, grammarAccess.getIntArrayAccess().getRightSquareBracketKeyword_2_2());
			}
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getIntArrayAccess().getNameEStringParserRuleCall_3_0());
				}
				lv_name_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getIntArrayRule());
					}
					set(
						$current,
						"name",
						lv_name_5_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='='
		{
			newLeafNode(otherlv_6, grammarAccess.getIntArrayAccess().getEqualsSignKeyword_4());
		}
		(
			otherlv_7='('
			{
				newLeafNode(otherlv_7, grammarAccess.getIntArrayAccess().getLeftParenthesisKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getIntArrayAccess().getValueEIntParserRuleCall_5_1_0());
					}
					lv_value_8_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getIntArrayRule());
						}
						add(
							$current,
							"value",
							lv_value_8_0,
							"org.xtext.Spice.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_9=','
			{
				newLeafNode(otherlv_9, grammarAccess.getIntArrayAccess().getCommaKeyword_5_2());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getIntArrayAccess().getValueEIntParserRuleCall_5_3_0());
					}
					lv_value_10_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getIntArrayRule());
						}
						add(
							$current,
							"value",
							lv_value_10_0,
							"org.xtext.Spice.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_11=','
				{
					newLeafNode(otherlv_11, grammarAccess.getIntArrayAccess().getCommaKeyword_5_4_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getIntArrayAccess().getValueEIntParserRuleCall_5_4_1_0());
						}
						lv_value_12_0=ruleEInt
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getIntArrayRule());
							}
							add(
								$current,
								"value",
								lv_value_12_0,
								"org.xtext.Spice.EInt");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_13=')'
			{
				newLeafNode(otherlv_13, grammarAccess.getIntArrayAccess().getRightParenthesisKeyword_5_5());
			}
		)
		otherlv_14=';'
		{
			newLeafNode(otherlv_14, grammarAccess.getIntArrayAccess().getSemicolonKeyword_6());
		}
	)
;

// Entry rule entryRuleDoubleBasic
entryRuleDoubleBasic returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDoubleBasicRule()); }
	iv_ruleDoubleBasic=ruleDoubleBasic
	{ $current=$iv_ruleDoubleBasic.current; }
	EOF;

// Rule DoubleBasic
ruleDoubleBasic returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_isObservable_0_0='observable'
				{
					newLeafNode(lv_isObservable_0_0, grammarAccess.getDoubleBasicAccess().getIsObservableObservableKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDoubleBasicRule());
					}
					setWithLastConsumed($current, "isObservable", lv_isObservable_0_0 != null, "observable");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getDoubleBasicAccess().getTypeEStringParserRuleCall_1_0());
				}
				lv_type_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDoubleBasicRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getDoubleBasicAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDoubleBasicRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='='
		{
			newLeafNode(otherlv_3, grammarAccess.getDoubleBasicAccess().getEqualsSignKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDoubleBasicAccess().getValueEDoubleParserRuleCall_4_0());
				}
				lv_value_4_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDoubleBasicRule());
					}
					set(
						$current,
						"value",
						lv_value_4_0,
						"org.xtext.Spice.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5=';'
		{
			newLeafNode(otherlv_5, grammarAccess.getDoubleBasicAccess().getSemicolonKeyword_5());
		}
	)
;

// Entry rule entryRuleDoubleArray
entryRuleDoubleArray returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDoubleArrayRule()); }
	iv_ruleDoubleArray=ruleDoubleArray
	{ $current=$iv_ruleDoubleArray.current; }
	EOF;

// Rule DoubleArray
ruleDoubleArray returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_isObservable_0_0='observable'
				{
					newLeafNode(lv_isObservable_0_0, grammarAccess.getDoubleArrayAccess().getIsObservableObservableKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDoubleArrayRule());
					}
					setWithLastConsumed($current, "isObservable", lv_isObservable_0_0 != null, "observable");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getDoubleArrayAccess().getTypeEStringParserRuleCall_1_0());
				}
				lv_type_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDoubleArrayRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_2='['
			{
				newLeafNode(otherlv_2, grammarAccess.getDoubleArrayAccess().getLeftSquareBracketKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getDoubleArrayAccess().getMultiplicityELongParserRuleCall_2_1_0());
					}
					lv_multiplicity_3_0=ruleELong
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getDoubleArrayRule());
						}
						set(
							$current,
							"multiplicity",
							lv_multiplicity_3_0,
							"org.xtext.Spice.ELong");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_4=']'
			{
				newLeafNode(otherlv_4, grammarAccess.getDoubleArrayAccess().getRightSquareBracketKeyword_2_2());
			}
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getDoubleArrayAccess().getNameEStringParserRuleCall_3_0());
				}
				lv_name_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDoubleArrayRule());
					}
					set(
						$current,
						"name",
						lv_name_5_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='='
		{
			newLeafNode(otherlv_6, grammarAccess.getDoubleArrayAccess().getEqualsSignKeyword_4());
		}
		(
			otherlv_7='('
			{
				newLeafNode(otherlv_7, grammarAccess.getDoubleArrayAccess().getLeftParenthesisKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getDoubleArrayAccess().getValueEDoubleParserRuleCall_5_1_0());
					}
					lv_value_8_0=ruleEDouble
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getDoubleArrayRule());
						}
						add(
							$current,
							"value",
							lv_value_8_0,
							"org.xtext.Spice.EDouble");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_9=','
			{
				newLeafNode(otherlv_9, grammarAccess.getDoubleArrayAccess().getCommaKeyword_5_2());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getDoubleArrayAccess().getValueEDoubleParserRuleCall_5_3_0());
					}
					lv_value_10_0=ruleEDouble
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getDoubleArrayRule());
						}
						add(
							$current,
							"value",
							lv_value_10_0,
							"org.xtext.Spice.EDouble");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_11=','
				{
					newLeafNode(otherlv_11, grammarAccess.getDoubleArrayAccess().getCommaKeyword_5_4_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getDoubleArrayAccess().getValueEDoubleParserRuleCall_5_4_1_0());
						}
						lv_value_12_0=ruleEDouble
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getDoubleArrayRule());
							}
							add(
								$current,
								"value",
								lv_value_12_0,
								"org.xtext.Spice.EDouble");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_13=')'
			{
				newLeafNode(otherlv_13, grammarAccess.getDoubleArrayAccess().getRightParenthesisKeyword_5_5());
			}
		)
		otherlv_14=';'
		{
			newLeafNode(otherlv_14, grammarAccess.getDoubleArrayAccess().getSemicolonKeyword_6());
		}
	)
;

// Entry rule entryRuleStringBasic
entryRuleStringBasic returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStringBasicRule()); }
	iv_ruleStringBasic=ruleStringBasic
	{ $current=$iv_ruleStringBasic.current; }
	EOF;

// Rule StringBasic
ruleStringBasic returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_isObservable_0_0='observable'
				{
					newLeafNode(lv_isObservable_0_0, grammarAccess.getStringBasicAccess().getIsObservableObservableKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStringBasicRule());
					}
					setWithLastConsumed($current, "isObservable", lv_isObservable_0_0 != null, "observable");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getStringBasicAccess().getTypeEStringParserRuleCall_1_0());
				}
				lv_type_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStringBasicRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getStringBasicAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStringBasicRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='='
		{
			newLeafNode(otherlv_3, grammarAccess.getStringBasicAccess().getEqualsSignKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getStringBasicAccess().getValueEStringParserRuleCall_4_0());
				}
				lv_value_4_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStringBasicRule());
					}
					set(
						$current,
						"value",
						lv_value_4_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5=';'
		{
			newLeafNode(otherlv_5, grammarAccess.getStringBasicAccess().getSemicolonKeyword_5());
		}
	)
;

// Entry rule entryRuleStringArray
entryRuleStringArray returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStringArrayRule()); }
	iv_ruleStringArray=ruleStringArray
	{ $current=$iv_ruleStringArray.current; }
	EOF;

// Rule StringArray
ruleStringArray returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_isObservable_0_0='observable'
				{
					newLeafNode(lv_isObservable_0_0, grammarAccess.getStringArrayAccess().getIsObservableObservableKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStringArrayRule());
					}
					setWithLastConsumed($current, "isObservable", lv_isObservable_0_0 != null, "observable");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getStringArrayAccess().getTypeEStringParserRuleCall_1_0());
				}
				lv_type_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStringArrayRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_2='['
			{
				newLeafNode(otherlv_2, grammarAccess.getStringArrayAccess().getLeftSquareBracketKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getStringArrayAccess().getMultiplicityELongParserRuleCall_2_1_0());
					}
					lv_multiplicity_3_0=ruleELong
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getStringArrayRule());
						}
						set(
							$current,
							"multiplicity",
							lv_multiplicity_3_0,
							"org.xtext.Spice.ELong");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_4=']'
			{
				newLeafNode(otherlv_4, grammarAccess.getStringArrayAccess().getRightSquareBracketKeyword_2_2());
			}
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getStringArrayAccess().getNameEStringParserRuleCall_3_0());
				}
				lv_name_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStringArrayRule());
					}
					set(
						$current,
						"name",
						lv_name_5_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='='
		{
			newLeafNode(otherlv_6, grammarAccess.getStringArrayAccess().getEqualsSignKeyword_4());
		}
		(
			otherlv_7='('
			{
				newLeafNode(otherlv_7, grammarAccess.getStringArrayAccess().getLeftParenthesisKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getStringArrayAccess().getValueEStringParserRuleCall_5_1_0());
					}
					lv_value_8_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getStringArrayRule());
						}
						add(
							$current,
							"value",
							lv_value_8_0,
							"org.xtext.Spice.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_9=','
			{
				newLeafNode(otherlv_9, grammarAccess.getStringArrayAccess().getCommaKeyword_5_2());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getStringArrayAccess().getValueEStringParserRuleCall_5_3_0());
					}
					lv_value_10_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getStringArrayRule());
						}
						add(
							$current,
							"value",
							lv_value_10_0,
							"org.xtext.Spice.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_11=','
				{
					newLeafNode(otherlv_11, grammarAccess.getStringArrayAccess().getCommaKeyword_5_4_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getStringArrayAccess().getValueEStringParserRuleCall_5_4_1_0());
						}
						lv_value_12_0=ruleEString
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getStringArrayRule());
							}
							add(
								$current,
								"value",
								lv_value_12_0,
								"org.xtext.Spice.EString");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_13=')'
			{
				newLeafNode(otherlv_13, grammarAccess.getStringArrayAccess().getRightParenthesisKeyword_5_5());
			}
		)
		otherlv_14=';'
		{
			newLeafNode(otherlv_14, grammarAccess.getStringArrayAccess().getSemicolonKeyword_6());
		}
	)
;

// Entry rule entryRuleBooleanBasic
entryRuleBooleanBasic returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBooleanBasicRule()); }
	iv_ruleBooleanBasic=ruleBooleanBasic
	{ $current=$iv_ruleBooleanBasic.current; }
	EOF;

// Rule BooleanBasic
ruleBooleanBasic returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_isObservable_0_0='observable'
				{
					newLeafNode(lv_isObservable_0_0, grammarAccess.getBooleanBasicAccess().getIsObservableObservableKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBooleanBasicRule());
					}
					setWithLastConsumed($current, "isObservable", lv_isObservable_0_0 != null, "observable");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getBooleanBasicAccess().getTypeEStringParserRuleCall_1_0());
				}
				lv_type_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBooleanBasicRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getBooleanBasicAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBooleanBasicRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='='
		{
			newLeafNode(otherlv_3, grammarAccess.getBooleanBasicAccess().getEqualsSignKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getBooleanBasicAccess().getValueEBooleanParserRuleCall_4_0());
				}
				lv_value_4_0=ruleEBoolean
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBooleanBasicRule());
					}
					set(
						$current,
						"value",
						lv_value_4_0,
						"org.xtext.Spice.EBoolean");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5=';'
		{
			newLeafNode(otherlv_5, grammarAccess.getBooleanBasicAccess().getSemicolonKeyword_5());
		}
	)
;

// Entry rule entryRuleBooleanArray
entryRuleBooleanArray returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBooleanArrayRule()); }
	iv_ruleBooleanArray=ruleBooleanArray
	{ $current=$iv_ruleBooleanArray.current; }
	EOF;

// Rule BooleanArray
ruleBooleanArray returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_isObservable_0_0='observable'
				{
					newLeafNode(lv_isObservable_0_0, grammarAccess.getBooleanArrayAccess().getIsObservableObservableKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBooleanArrayRule());
					}
					setWithLastConsumed($current, "isObservable", lv_isObservable_0_0 != null, "observable");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getBooleanArrayAccess().getTypeEStringParserRuleCall_1_0());
				}
				lv_type_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBooleanArrayRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_2='['
			{
				newLeafNode(otherlv_2, grammarAccess.getBooleanArrayAccess().getLeftSquareBracketKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBooleanArrayAccess().getMultiplicityELongParserRuleCall_2_1_0());
					}
					lv_multiplicity_3_0=ruleELong
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBooleanArrayRule());
						}
						set(
							$current,
							"multiplicity",
							lv_multiplicity_3_0,
							"org.xtext.Spice.ELong");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_4=']'
			{
				newLeafNode(otherlv_4, grammarAccess.getBooleanArrayAccess().getRightSquareBracketKeyword_2_2());
			}
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getBooleanArrayAccess().getNameEStringParserRuleCall_3_0());
				}
				lv_name_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBooleanArrayRule());
					}
					set(
						$current,
						"name",
						lv_name_5_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='='
		{
			newLeafNode(otherlv_6, grammarAccess.getBooleanArrayAccess().getEqualsSignKeyword_4());
		}
		(
			otherlv_7='('
			{
				newLeafNode(otherlv_7, grammarAccess.getBooleanArrayAccess().getLeftParenthesisKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBooleanArrayAccess().getValueEBooleanParserRuleCall_5_1_0());
					}
					lv_value_8_0=ruleEBoolean
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBooleanArrayRule());
						}
						add(
							$current,
							"value",
							lv_value_8_0,
							"org.xtext.Spice.EBoolean");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_9=','
			{
				newLeafNode(otherlv_9, grammarAccess.getBooleanArrayAccess().getCommaKeyword_5_2());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBooleanArrayAccess().getValueEBooleanParserRuleCall_5_3_0());
					}
					lv_value_10_0=ruleEBoolean
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBooleanArrayRule());
						}
						add(
							$current,
							"value",
							lv_value_10_0,
							"org.xtext.Spice.EBoolean");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_11=','
				{
					newLeafNode(otherlv_11, grammarAccess.getBooleanArrayAccess().getCommaKeyword_5_4_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getBooleanArrayAccess().getValueEBooleanParserRuleCall_5_4_1_0());
						}
						lv_value_12_0=ruleEBoolean
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getBooleanArrayRule());
							}
							add(
								$current,
								"value",
								lv_value_12_0,
								"org.xtext.Spice.EBoolean");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_13=')'
			{
				newLeafNode(otherlv_13, grammarAccess.getBooleanArrayAccess().getRightParenthesisKeyword_5_5());
			}
		)
		otherlv_14=';'
		{
			newLeafNode(otherlv_14, grammarAccess.getBooleanArrayAccess().getSemicolonKeyword_6());
		}
	)
;

// Entry rule entryRuleXmod_Action
entryRuleXmod_Action returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getXmod_ActionRule()); }
	iv_ruleXmod_Action=ruleXmod_Action
	{ $current=$iv_ruleXmod_Action.current; }
	EOF;

// Rule Xmod_Action
ruleXmod_Action returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Action'
		{
			newLeafNode(otherlv_0, grammarAccess.getXmod_ActionAccess().getActionKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getXmod_ActionAccess().getNameEStringParserRuleCall_1_0());
				}
				lv_name_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getXmod_ActionRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getXmod_ActionAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getXmod_ActionAccess().getOperationsXmod_OperationCallParserRuleCall_3_0());
				}
				lv_operations_3_0=ruleXmod_OperationCall
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getXmod_ActionRule());
					}
					add(
						$current,
						"operations",
						lv_operations_3_0,
						"org.xtext.Spice.Xmod_OperationCall");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getXmod_ActionAccess().getOperationsXmod_OperationCallParserRuleCall_4_0());
				}
				lv_operations_4_0=ruleXmod_OperationCall
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getXmod_ActionRule());
					}
					add(
						$current,
						"operations",
						lv_operations_4_0,
						"org.xtext.Spice.Xmod_OperationCall");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getXmod_ActionAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleXmod_OperationDef
entryRuleXmod_OperationDef returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getXmod_OperationDefRule()); }
	iv_ruleXmod_OperationDef=ruleXmod_OperationDef
	{ $current=$iv_ruleXmod_OperationDef.current; }
	EOF;

// Rule Xmod_OperationDef
ruleXmod_OperationDef returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getXmod_OperationDefAccess().getNameEStringParserRuleCall_0_0());
				}
				lv_name_0_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getXmod_OperationDefRule());
					}
					set(
						$current,
						"name",
						lv_name_0_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1='('
		{
			newLeafNode(otherlv_1, grammarAccess.getXmod_OperationDefAccess().getLeftParenthesisKeyword_1());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getXmod_OperationDefAccess().getParametersTagEStringParserRuleCall_2_0_0());
					}
					lv_parametersTag_2_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getXmod_OperationDefRule());
						}
						add(
							$current,
							"parametersTag",
							lv_parametersTag_2_0,
							"org.xtext.Spice.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_3=','
				{
					newLeafNode(otherlv_3, grammarAccess.getXmod_OperationDefAccess().getCommaKeyword_2_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getXmod_OperationDefAccess().getParametersTagEStringParserRuleCall_2_1_1_0());
						}
						lv_parametersTag_4_0=ruleEString
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getXmod_OperationDefRule());
							}
							add(
								$current,
								"parametersTag",
								lv_parametersTag_4_0,
								"org.xtext.Spice.EString");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_5=')'
		{
			newLeafNode(otherlv_5, grammarAccess.getXmod_OperationDefAccess().getRightParenthesisKeyword_3());
		}
		otherlv_6='on'
		{
			newLeafNode(otherlv_6, grammarAccess.getXmod_OperationDefAccess().getOnKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getXmod_OperationDefAccess().getObjectTagEStringParserRuleCall_5_0());
				}
				lv_objectTag_7_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getXmod_OperationDefRule());
					}
					set(
						$current,
						"objectTag",
						lv_objectTag_7_0,
						"org.xtext.Spice.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_8='returns'
			{
				newLeafNode(otherlv_8, grammarAccess.getXmod_OperationDefAccess().getReturnsKeyword_6_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getXmod_OperationDefAccess().getReturnTagEStringParserRuleCall_6_1_0());
					}
					lv_returnTag_9_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getXmod_OperationDefRule());
						}
						set(
							$current,
							"returnTag",
							lv_returnTag_9_0,
							"org.xtext.Spice.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getXmod_OperationDefAccess().getExceptionsXmod_ExceptionParserRuleCall_7_0_0());
					}
					lv_exceptions_10_0=ruleXmod_Exception
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getXmod_OperationDefRule());
						}
						add(
							$current,
							"exceptions",
							lv_exceptions_10_0,
							"org.xtext.Spice.Xmod_Exception");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getXmod_OperationDefAccess().getExceptionsXmod_ExceptionParserRuleCall_7_1_0());
					}
					lv_exceptions_11_0=ruleXmod_Exception
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getXmod_OperationDefRule());
						}
						add(
							$current,
							"exceptions",
							lv_exceptions_11_0,
							"org.xtext.Spice.Xmod_Exception");
						afterParserOrEnumRuleCall();
					}
				)
			)*
		)?
	)
;

// Entry rule entryRuleXmod_OperationCall
entryRuleXmod_OperationCall returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getXmod_OperationCallRule()); }
	iv_ruleXmod_OperationCall=ruleXmod_OperationCall
	{ $current=$iv_ruleXmod_OperationCall.current; }
	EOF;

// Rule Xmod_OperationCall
ruleXmod_OperationCall returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='call'
		{
			newLeafNode(otherlv_0, grammarAccess.getXmod_OperationCallAccess().getCallKeyword_0());
		}
		{
			newCompositeNode(grammarAccess.getXmod_OperationCallAccess().getXmod_OperationDefParserRuleCall_1());
		}
		this_Xmod_OperationDef_1=ruleXmod_OperationDef
		{
			$current = $this_Xmod_OperationDef_1.current;
			afterParserOrEnumRuleCall();
		}
		otherlv_2=';'
		{
			newLeafNode(otherlv_2, grammarAccess.getXmod_OperationCallAccess().getSemicolonKeyword_2());
		}
	)
;

// Entry rule entryRuleXmod_Exception
entryRuleXmod_Exception returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getXmod_ExceptionRule()); }
	iv_ruleXmod_Exception=ruleXmod_Exception
	{ $current=$iv_ruleXmod_Exception.current; }
	EOF;

// Rule Xmod_Exception
ruleXmod_Exception returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='onError'
		{
			newLeafNode(otherlv_0, grammarAccess.getXmod_ExceptionAccess().getOnErrorKeyword_0());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getXmod_ExceptionAccess().getKindXmod_ExceptionKind_UnfilteredParserRuleCall_1_0_0());
					}
					lv_kind_1_0=ruleXmod_ExceptionKind_Unfiltered
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getXmod_ExceptionRule());
						}
						set(
							$current,
							"kind",
							lv_kind_1_0,
							"org.xtext.Spice.Xmod_ExceptionKind_Unfiltered");
						afterParserOrEnumRuleCall();
					}
				)
			)
			    |
			(
				(
					(
						{
							newCompositeNode(grammarAccess.getXmod_ExceptionAccess().getKindXmod_ExceptionKind_FilteredParserRuleCall_1_1_0_0());
						}
						lv_kind_2_0=ruleXmod_ExceptionKind_Filtered
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getXmod_ExceptionRule());
							}
							set(
								$current,
								"kind",
								lv_kind_2_0,
								"org.xtext.Spice.Xmod_ExceptionKind_Filtered");
							afterParserOrEnumRuleCall();
						}
					)
				)
				otherlv_3='('
				{
					newLeafNode(otherlv_3, grammarAccess.getXmod_ExceptionAccess().getLeftParenthesisKeyword_1_1_1());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getXmod_ExceptionAccess().getFilterEStringParserRuleCall_1_1_2_0());
						}
						lv_filter_4_0=ruleEString
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getXmod_ExceptionRule());
							}
							set(
								$current,
								"filter",
								lv_filter_4_0,
								"org.xtext.Spice.EString");
							afterParserOrEnumRuleCall();
						}
					)
				)
				otherlv_5=')'
				{
					newLeafNode(otherlv_5, grammarAccess.getXmod_ExceptionAccess().getRightParenthesisKeyword_1_1_3());
				}
			)
		)
		(
			otherlv_6='call'
			{
				newLeafNode(otherlv_6, grammarAccess.getXmod_ExceptionAccess().getCallKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getXmod_ExceptionAccess().getCalledOperationXmod_OperationDefParserRuleCall_2_1_0());
					}
					lv_calledOperation_7_0=ruleXmod_OperationDef
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getXmod_ExceptionRule());
						}
						set(
							$current,
							"calledOperation",
							lv_calledOperation_7_0,
							"org.xtext.Spice.Xmod_OperationDef");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_8='then'
		{
			newLeafNode(otherlv_8, grammarAccess.getXmod_ExceptionAccess().getThenKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getXmod_ExceptionAccess().getReactionXmod_ExceptionReactionEnumRuleCall_4_0());
				}
				lv_reaction_9_0=ruleXmod_ExceptionReaction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getXmod_ExceptionRule());
					}
					set(
						$current,
						"reaction",
						lv_reaction_9_0,
						"org.xtext.Spice.Xmod_ExceptionReaction");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleXmod_ExceptionKind_Filtered
entryRuleXmod_ExceptionKind_Filtered returns [String current=null]:
	{ newCompositeNode(grammarAccess.getXmod_ExceptionKind_FilteredRule()); }
	iv_ruleXmod_ExceptionKind_Filtered=ruleXmod_ExceptionKind_Filtered
	{ $current=$iv_ruleXmod_ExceptionKind_Filtered.current.getText(); }
	EOF;

// Rule Xmod_ExceptionKind_Filtered
ruleXmod_ExceptionKind_Filtered returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw='methodException'
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getXmod_ExceptionKind_FilteredAccess().getMethodExceptionKeyword());
	}
;

// Entry rule entryRuleXmod_ExceptionKind_Unfiltered
entryRuleXmod_ExceptionKind_Unfiltered returns [String current=null]:
	{ newCompositeNode(grammarAccess.getXmod_ExceptionKind_UnfilteredRule()); }
	iv_ruleXmod_ExceptionKind_Unfiltered=ruleXmod_ExceptionKind_Unfiltered
	{ $current=$iv_ruleXmod_ExceptionKind_Unfiltered.current.getText(); }
	EOF;

// Rule Xmod_ExceptionKind_Unfiltered
ruleXmod_ExceptionKind_Unfiltered returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='other'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getXmod_ExceptionKind_UnfilteredAccess().getOtherKeyword_0());
		}
		    |
		kw='unknownNamespace'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getXmod_ExceptionKind_UnfilteredAccess().getUnknownNamespaceKeyword_1());
		}
		    |
		kw='objectNotFound'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getXmod_ExceptionKind_UnfilteredAccess().getObjectNotFoundKeyword_2());
		}
		    |
		kw='methodNotFound'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getXmod_ExceptionKind_UnfilteredAccess().getMethodNotFoundKeyword_3());
		}
		    |
		kw='parametersNotMatching'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getXmod_ExceptionKind_UnfilteredAccess().getParametersNotMatchingKeyword_4());
		}
		    |
		kw='returnTypeNotMatching'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getXmod_ExceptionKind_UnfilteredAccess().getReturnTypeNotMatchingKeyword_5());
		}
	)
;

// Entry rule entryRuleEDouble
entryRuleEDouble returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEDoubleRule()); }
	iv_ruleEDouble=ruleEDouble
	{ $current=$iv_ruleEDouble.current.getText(); }
	EOF;

// Rule EDouble
ruleEDouble returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getEDoubleAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_1());
		}
		kw='.'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEDoubleAccess().getFullStopKeyword_2());
		}
		this_INT_3=RULE_INT
		{
			$current.merge(this_INT_3);
		}
		{
			newLeafNode(this_INT_3, grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_3());
		}
		(
			(
				kw='e'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleAccess().getEKeyword_4_0_0());
				}
				    |
				kw='E'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleAccess().getEKeyword_4_0_1());
				}
			)
			(
				kw='-'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleAccess().getHyphenMinusKeyword_4_1());
				}
			)?
			this_INT_7=RULE_INT
			{
				$current.merge(this_INT_7);
			}
			{
				newLeafNode(this_INT_7, grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_4_2());
			}
		)?
	)
;

// Entry rule entryRuleEInt
entryRuleEInt returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEIntRule()); }
	iv_ruleEInt=ruleEInt
	{ $current=$iv_ruleEInt.current.getText(); }
	EOF;

// Rule EInt
ruleEInt returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	this_INT_0=RULE_INT
	{
		$current.merge(this_INT_0);
	}
	{
		newLeafNode(this_INT_0, grammarAccess.getEIntAccess().getINTTerminalRuleCall());
	}
;

// Entry rule entryRuleELong
entryRuleELong returns [String current=null]:
	{ newCompositeNode(grammarAccess.getELongRule()); }
	iv_ruleELong=ruleELong
	{ $current=$iv_ruleELong.current.getText(); }
	EOF;

// Rule ELong
ruleELong returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	this_INT_0=RULE_INT
	{
		$current.merge(this_INT_0);
	}
	{
		newLeafNode(this_INT_0, grammarAccess.getELongAccess().getINTTerminalRuleCall());
	}
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleEBoolean
entryRuleEBoolean returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEBooleanRule()); }
	iv_ruleEBoolean=ruleEBoolean
	{ $current=$iv_ruleEBoolean.current.getText(); }
	EOF;

// Rule EBoolean
ruleEBoolean returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='true'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanAccess().getTrueKeyword_0());
		}
		    |
		kw='false'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanAccess().getFalseKeyword_1());
		}
	)
;

// Rule Xmod_ExceptionReaction
ruleXmod_ExceptionReaction returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='continue'
			{
				$current = grammarAccess.getXmod_ExceptionReactionAccess().getContinueEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getXmod_ExceptionReactionAccess().getContinueEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='skip'
			{
				$current = grammarAccess.getXmod_ExceptionReactionAccess().getSkipEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getXmod_ExceptionReactionAccess().getSkipEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='exit'
			{
				$current = grammarAccess.getXmod_ExceptionReactionAccess().getExitEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getXmod_ExceptionReactionAccess().getExitEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='localstop'
			{
				$current = grammarAccess.getXmod_ExceptionReactionAccess().getLocalstopEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getXmod_ExceptionReactionAccess().getLocalstopEnumLiteralDeclaration_3());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
